import assert from "node:assert/strict";
import test from "node:test";
import { DENTAL_PACK, DRIVING_SCHOOL_PACK, INDUSTRY_PACK_FIXTURES } from "./industry-pack-fixtures.js";
import { createIndustryPackRegistry } from "./industry-pack-registry.js";
import { resolveIndustryPack, validateIndustryPackManifest, validateIndustryPackOverrides } from "./industry-packs.js";
import { buildIndustryPackMaterializationPlan } from "./industry-pack-materialization.js";
import { findRequirementAvailability } from "./requirement-availability.js";

test("includes the universal acceptance pack set", () => { assert.deepEqual(new Set(INDUSTRY_PACK_FIXTURES.map((pack) => pack.id)), new Set(["driving-school", "dental", "hospital", "fitness", "transport", "charter", "salon"])); });

test("accepts the required multi-resource pack fixtures", () => { for (const pack of INDUSTRY_PACK_FIXTURES) { assert.deepEqual(validateIndustryPackManifest(pack), []); assert.ok(pack.serviceTemplates.some((service) => service.requirements.length >= 2)); } });
test("pack fixtures expose distinct safe navigation and dashboard contributions", () => { const ids = INDUSTRY_PACK_FIXTURES.map((pack) => pack.navigation.map((item) => item.id).join(",")); assert.equal(new Set(ids).size, INDUSTRY_PACK_FIXTURES.length); for (const pack of INDUSTRY_PACK_FIXTURES) { assert.ok(pack.navigation.length >= 2); assert.ok(pack.dashboards.every((dashboard) => dashboard.metricIds.length > 0)); } });
test("rejects a service template with an unknown selector", () => { const invalid = { ...DENTAL_PACK, serviceTemplates: [{ ...DENTAL_PACK.serviceTemplates[0]!, requirements: [{ kind: "resource" as const, label: "Unknown", quantity: 1, capabilityKey: "missing.capability" }] }] }; assert.match(validateIndustryPackManifest(invalid).join("; "), /unknown resource or capability/iu); });
test("rejects executable pack navigation paths", () => { const invalid = { ...DENTAL_PACK, navigation: [{ ...DENTAL_PACK.navigation[0]!, href: "javascript:alert(1)" }] }; assert.match(validateIndustryPackManifest(invalid).join("; "), /internal HTML path/iu); });
test("resolves the latest registered pack version without accepting duplicates", () => { const registry = createIndustryPackRegistry([DRIVING_SCHOOL_PACK]); const next = { ...DRIVING_SCHOOL_PACK, version: "1.1.0" as const }; registry.register(next); assert.equal(registry.read("driving-school")?.version, "1.1.0"); assert.equal(registry.read("driving-school", "1.0.0")?.version, "1.0.0"); assert.throws(() => registry.register(next), /already registered/iu); });
test("allows only bounded terminology and theme overrides", () => { const overrides = { terminology: { service: "Lesson" }, theme: { accent: "#111827" } }; assert.deepEqual(validateIndustryPackOverrides(DRIVING_SCHOOL_PACK, overrides), []); assert.equal(resolveIndustryPack(DRIVING_SCHOOL_PACK, overrides).terminology.service, "Lesson"); assert.match(validateIndustryPackOverrides(DRIVING_SCHOOL_PACK, { terminology: { unknown: "Nope" } }).join("; "), /not allowed/iu); });
test("builds deterministic services, default variants, and requirement slots", () => { const plan = buildIndustryPackMaterializationPlan(DRIVING_SCHOOL_PACK, "tenant-1"); assert.equal(plan.services.length, 1); assert.equal(plan.variants.length, 1); assert.equal(plan.requirements.length, 2); assert.equal(plan.requirements[0]?.variantId, plan.variants[0]?.id); assert.equal(buildIndustryPackMaterializationPlan(DRIVING_SCHOOL_PACK, "tenant-1").services[0]?.id, plan.services[0]?.id); });
test("every pack produces a complete schedulable slot and explains a missing resource", () => { for (const pack of INDUSTRY_PACK_FIXTURES) { const plan = buildIndustryPackMaterializationPlan(pack, "tenant-1"); const resources = plan.requirements.map((requirement, index) => ({ id: `${pack.id}-resource-${index}`, resourceType: requirement.resourceType ?? "staff", capabilities: requirement.capabilityKey ? [requirement.capabilityKey] : [] })); const from = new Date("2026-08-14T09:00:00.000Z"); const durationMinutes = plan.services[0]!.durationMinutes; const window = { from, to: new Date(from.getTime() + durationMinutes * 60_000), durationMinutes, stepMinutes: durationMinutes }; const ready = findRequirementAvailability(plan.requirements.map((requirement) => ({ id: requirement.id, quantity: requirement.quantity ?? 1, resourceType: requirement.resourceType ?? null, capabilityKey: requirement.capabilityKey ?? null })), resources, [], window); assert.equal(ready.slots.length, 1, `${pack.id} should have one feasible slot`); assert.equal(new Set(ready.slots[0]!.assignments.flatMap((assignment) => assignment.resourceIds)).size, resources.length); const missing = findRequirementAvailability(plan.requirements.map((requirement) => ({ id: requirement.id, quantity: requirement.quantity ?? 1, resourceType: requirement.resourceType ?? null, capabilityKey: requirement.capabilityKey ?? null })), resources.slice(1), [], window); assert.equal(missing.slots.length, 0, `${pack.id} should reject an incomplete assignment`); assert.ok(missing.rejected.length > 0); } });
