// Ownership: deterministic acceptance fixtures for shared shell and booking-kernel composition.

import type { IndustryPackManifest } from "./industry-packs.js";

const emptyExtensions = { workflows: [], forms: [], outcomes: [], permissions: [], automations: [], reports: [], migrations: [] } as const;
type PackUi = Pick<IndustryPackManifest, "navigation" | "dashboards">;
function pack(core: Pick<IndustryPackManifest, "id" | "displayName" | "theme" | "resourceTypes" | "capabilities" | "serviceTemplates">, ui: PackUi): IndustryPackManifest { return { ...core, version: "1.0.0", schemaVersion: 1, supportedLocales: ["en-KE"], terminology: { service: "Service", customer: "Customer" }, ...ui, ...emptyExtensions }; }

export const DRIVING_SCHOOL_PACK = pack({ id: "driving-school", displayName: "Driving School", theme: { accent: "#f59e0b", accentSoft: "#fffbeb" }, resourceTypes: [{ id: "vehicle", label: "Vehicle" }], capabilities: [{ id: "driving.instructor", label: "Driving instructor" }, { id: "driving.manual", label: "Manual licence" }], serviceTemplates: [{ id: "driving-school.lesson", name: "Driving lesson", bookingMode: "appointment", durationMinutes: 60, requirements: [{ kind: "resource", label: "Instructor", quantity: 1, capabilityKey: "driving.instructor" }, { kind: "resource", label: "Vehicle", quantity: 1, resourceType: "vehicle" }] }] }, { navigation: [{ id: "driving-school.lessons", label: "Lessons", href: "./bookings.html" }, { id: "driving-school.vehicles", label: "Vehicles", href: "./resources.html" }], dashboards: [{ id: "driving-school.progress", title: "Lesson progress", metricIds: ["lessons.today", "students.progress"] }] });
export const DENTAL_PACK = pack({ id: "dental", displayName: "Dental", theme: { accent: "#06b6d4", accentSoft: "#ecfeff" }, resourceTypes: [{ id: "dental-chair", label: "Dental chair" }], capabilities: [{ id: "dental.provider", label: "Dental provider" }], serviceTemplates: [{ id: "dental.appointment", name: "Dental appointment", bookingMode: "appointment", durationMinutes: 45, requirements: [{ kind: "resource", label: "Provider", quantity: 1, capabilityKey: "dental.provider" }, { kind: "resource", label: "Chair", quantity: 1, resourceType: "dental-chair" }] }] }, { navigation: [{ id: "dental.appointments", label: "Appointments", href: "./bookings.html" }, { id: "dental.resources", label: "Rooms & chairs", href: "./resources.html" }], dashboards: [{ id: "dental.clinic", title: "Clinic today", metricIds: ["appointments.today", "patients.waiting"] }] });
export const HOSPITAL_PACK = pack({ id: "hospital", displayName: "Hospital", theme: { accent: "#0d9488", accentSoft: "#f0fdfa" }, resourceTypes: [{ id: "hospital-room", label: "Consultation room" }], capabilities: [{ id: "hospital.clinician", label: "Clinician" }, { id: "hospital.specialist", label: "Specialist" }], serviceTemplates: [{ id: "hospital.consultation", name: "Hospital consultation", bookingMode: "appointment", durationMinutes: 30, requirements: [{ kind: "resource", label: "Clinician", quantity: 1, capabilityKey: "hospital.clinician" }, { kind: "resource", label: "Room", quantity: 1, resourceType: "hospital-room" }] }] }, { navigation: [{ id: "hospital.consultations", label: "Consultations", href: "./bookings.html" }, { id: "hospital.rooms", label: "Rooms & equipment", href: "./resources.html" }], dashboards: [{ id: "hospital.care", title: "Care today", metricIds: ["appointments.today", "patients.waiting"] }] });
export const FITNESS_PACK = pack({ id: "fitness", displayName: "Fitness", theme: { accent: "#f97316", accentSoft: "#fff7ed" }, resourceTypes: [{ id: "fitness-studio", label: "Studio" }], capabilities: [{ id: "fitness.trainer", label: "Trainer" }], serviceTemplates: [{ id: "fitness.class", name: "Fitness class", bookingMode: "occurrence", durationMinutes: 60, requirements: [{ kind: "resource", label: "Trainer", quantity: 1, capabilityKey: "fitness.trainer" }, { kind: "resource", label: "Studio", quantity: 1, resourceType: "fitness-studio" }] }] }, { navigation: [{ id: "fitness.classes", label: "Classes", href: "./occurrences.html" }, { id: "fitness.studios", label: "Studios & trainers", href: "./resources.html" }], dashboards: [{ id: "fitness.attendance", title: "Attendance today", metricIds: ["classes.today", "places.remaining"] }] });
export const TRANSPORT_PACK = pack({ id: "transport", displayName: "Transport", theme: { accent: "#0ea5e9", accentSoft: "#f0f9ff" }, resourceTypes: [{ id: "bus", label: "Bus or matatu" }], capabilities: [{ id: "transport.driver", label: "Licensed driver" }], serviceTemplates: [{ id: "transport.trip", name: "Scheduled trip", bookingMode: "occurrence", durationMinutes: 90, requirements: [{ kind: "resource", label: "Driver", quantity: 1, capabilityKey: "transport.driver" }, { kind: "resource", label: "Vehicle", quantity: 1, resourceType: "bus" }] }] }, { navigation: [{ id: "transport.trips", label: "Trips", href: "./occurrences.html" }, { id: "transport.fleet", label: "Fleet", href: "./resources.html" }], dashboards: [{ id: "transport.dispatch", title: "Dispatch today", metricIds: ["trips.today", "reservations.remaining"] }] });
export const CHARTER_PACK = pack({ id: "charter", displayName: "Charter", theme: { accent: "#2563eb", accentSoft: "#eff6ff" }, resourceTypes: [{ id: "charter-vehicle", label: "Charter vehicle" }], capabilities: [{ id: "charter.crew", label: "Crew member" }], serviceTemplates: [{ id: "charter.journey", name: "Charter journey", bookingMode: "occurrence", durationMinutes: 180, requirements: [{ kind: "resource", label: "Crew", quantity: 1, capabilityKey: "charter.crew" }, { kind: "resource", label: "Vehicle", quantity: 1, resourceType: "charter-vehicle" }] }] }, { navigation: [{ id: "charter.journeys", label: "Journeys", href: "./occurrences.html" }, { id: "charter.fleet", label: "Fleet & crew", href: "./resources.html" }], dashboards: [{ id: "charter.operations", title: "Charter operations", metricIds: ["journeys.today", "vehicles.available"] }] });
export const SALON_PACK = pack({ id: "salon", displayName: "Salon & Beauty", theme: { accent: "#f43f5e", accentSoft: "#fff1f2" }, resourceTypes: [{ id: "salon-station", label: "Salon station" }], capabilities: [{ id: "salon.stylist", label: "Stylist" }], serviceTemplates: [{ id: "salon.service", name: "Beauty service", bookingMode: "appointment", durationMinutes: 60, requirements: [{ kind: "resource", label: "Stylist", quantity: 1, capabilityKey: "salon.stylist" }, { kind: "resource", label: "Station", quantity: 1, resourceType: "salon-station" }] }] }, { navigation: [{ id: "salon.appointments", label: "Appointments", href: "./bookings.html" }, { id: "salon.team", label: "Team & stations", href: "./resources.html" }], dashboards: [{ id: "salon.day", title: "Studio today", metricIds: ["appointments.today", "stations.utilization"] }] });
export const INDUSTRY_PACK_FIXTURES: readonly IndustryPackManifest[] = [DRIVING_SCHOOL_PACK, DENTAL_PACK, HOSPITAL_PACK, FITNESS_PACK, TRANSPORT_PACK, CHARTER_PACK, SALON_PACK];
