// Ownership: public QR booking client. It only carries opaque hold tokens and public destination data.

import { publicQrPath, type AvailabilityResponse, type PublicBookingConfirmationResponse, type PublicBookingHoldResponse, type PublicManageBookingResponse, type PublicOccurrenceReservationResponse, type PublicOccurrencesResponse, type PublicQrBookingResponse, type RequirementAvailabilityResponse } from "@bookingapp/contracts";
import { userFacingMessage } from "./user-messages.js";

export type GuestFetcher = (url: string, init?: { method?: "POST"; headers?: Record<string, string>; body?: string }) => Promise<{ ok: boolean; status: number; json(): Promise<unknown> }>;
export type GuestState<T> = { kind: "ready"; value: T } | { kind: "unavailable" | "error"; message: string };
function errorMessage(status: number, error?: { code?: string; message?: string }): string { return userFacingMessage(status, error, "We could not complete that booking request."); }
export async function fetchGuestDestination(fetcher: GuestFetcher, baseUrl: string, publicCode: string): Promise<GuestState<NonNullable<PublicQrBookingResponse["data"]>>> {
  const response = await fetcher(`${baseUrl}${publicQrPath(publicCode)}`);
  const body = (await response.json()) as PublicQrBookingResponse;
  if (body.data) return { kind: "ready", value: body.data };
  return { kind: "unavailable", message: errorMessage(response.status, body.error ?? undefined) };
}
export async function fetchGuestOccurrences(fetcher: GuestFetcher, baseUrl: string, publicCode: string): Promise<GuestState<NonNullable<PublicOccurrencesResponse["data"]>>> {
  try { const response = await fetcher(`${baseUrl}/v1/public/qr/${encodeURIComponent(publicCode)}/occurrences`); const body = (await response.json()) as PublicOccurrencesResponse; if (body.data) return { kind: "ready", value: body.data }; return { kind: response.status === 404 || response.status === 410 ? "unavailable" : "error", message: errorMessage(response.status, body.error ?? undefined) }; } catch { return { kind: "error", message: "We could not load the available sessions. Please try again." }; }
}
export async function createGuestOccurrenceReservation(fetcher: GuestFetcher, baseUrl: string, publicCode: string, occurrenceId: string, input: { customerName: string; quantity: number; idempotencyKey: string; contact?: { channel: "email" | "sms" | "voice"; destination: string; consentGranted: boolean } }): Promise<GuestState<NonNullable<PublicOccurrenceReservationResponse["data"]>>> {
  const response = await fetcher(`${baseUrl}/v1/public/qr/${encodeURIComponent(publicCode)}/occurrences/${encodeURIComponent(occurrenceId)}/reservations`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) });
  const body = (await response.json()) as PublicOccurrenceReservationResponse;
  if (body.data) return { kind: "ready", value: body.data };
  return { kind: response.status === 404 || response.status === 410 ? "unavailable" : "error", message: errorMessage(response.status, body.error ?? undefined) };
}
export async function fetchGuestAvailability(fetcher: GuestFetcher, baseUrl: string, publicCode: string, input: { from: string; to: string; durationMinutes: number; stepMinutes?: number; requiredResourceCount?: number }): Promise<GuestState<NonNullable<AvailabilityResponse["data"]>>> {
  const query = new URLSearchParams({ from: input.from, to: input.to, durationMinutes: String(input.durationMinutes), stepMinutes: String(input.stepMinutes ?? input.durationMinutes), requiredResourceCount: String(input.requiredResourceCount ?? 1) });
  const response = await fetcher(`${baseUrl}/v1/public/qr/${encodeURIComponent(publicCode)}/availability?${query.toString()}`);
  const body = (await response.json()) as AvailabilityResponse;
  if (body.data) return { kind: "ready", value: body.data };
  return { kind: response.status === 404 || response.status === 410 ? "unavailable" : "error", message: errorMessage(response.status, body.error ?? undefined) };
}
export async function fetchGuestRequirementAvailability(fetcher: GuestFetcher, baseUrl: string, publicCode: string, input: { from: string; to: string; durationMinutes: number; stepMinutes?: number; variantId?: string | null }): Promise<GuestState<NonNullable<RequirementAvailabilityResponse["data"]>>> { const query = new URLSearchParams({ from: input.from, to: input.to, durationMinutes: String(input.durationMinutes), stepMinutes: String(input.stepMinutes ?? input.durationMinutes) }); if (input.variantId) query.set("variantId", input.variantId); const response = await fetcher(`${baseUrl}/v1/public/qr/${encodeURIComponent(publicCode)}/requirement-availability?${query.toString()}`); const body = (await response.json()) as RequirementAvailabilityResponse; if (body.data) return { kind: "ready", value: body.data }; return { kind: response.status === 404 || response.status === 410 ? "unavailable" : "error", message: errorMessage(response.status, body.error ?? undefined) }; }
export function shouldFallbackToLegacyAvailability(data: NonNullable<RequirementAvailabilityResponse["data"]>): boolean { return data.slots.length === 0 && data.rejected.length === 0; }
export function formatRequirementAvailabilityMessage(data: NonNullable<RequirementAvailabilityResponse["data"]>): string { const reasons = new Set(data.rejected.map((item) => item.reason)); if (reasons.has("INSUFFICIENT_RESOURCES") && reasons.has("NO_COMPATIBLE_RESOURCES")) return "That time is not available. Please choose another time or contact us."; if (reasons.has("INSUFFICIENT_RESOURCES")) return "That time is already full. Please choose another time."; if (reasons.has("NO_COMPATIBLE_RESOURCES")) return "That service is not available at this time. Please choose another option or contact us."; return "That time is not available. Please choose another time."; }
export function formatRequirementAssignmentSummary(assignments: readonly { requirementId: string; resourceIds: readonly string[]; requirementLabel?: string }[]): string { if (!assignments.length) return ""; const labels = assignments.map((assignment) => assignment.requirementLabel?.trim()).filter((label): label is string => Boolean(label)); return labels.length ? `This time includes ${labels.join(", ")}.` : "This time includes all required resources."; }
export async function createGuestHold(fetcher: GuestFetcher, baseUrl: string, publicCode: string, input: { customerName: string; serviceName: string; startsAt: string; endsAt: string; idempotencyKey: string; resourceIds?: readonly string[]; variantId?: string | null; requirementAssignments?: readonly { requirementId: string; resourceIds: readonly string[] }[] }): Promise<GuestState<NonNullable<PublicBookingHoldResponse["data"]>>> {
  const response = await fetcher(`${baseUrl}/v1/public/qr/${encodeURIComponent(publicCode)}/booking-holds`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) });
  const body = (await response.json()) as PublicBookingHoldResponse;
  if (body.data) return { kind: "ready", value: body.data };
  return { kind: response.status === 404 || response.status === 410 ? "unavailable" : "error", message: errorMessage(response.status, body.error ?? undefined) };
}
export async function confirmGuestHold(fetcher: GuestFetcher, baseUrl: string, publicCode: string, holdId: string, holdToken: string, idempotencyKey: string, contact?: { channel: "email" | "sms" | "voice"; destination: string; consentGranted: boolean }): Promise<GuestState<NonNullable<PublicBookingConfirmationResponse["data"]>>> {
  const response = await fetcher(`${baseUrl}/v1/public/qr/${encodeURIComponent(publicCode)}/booking-holds/${encodeURIComponent(holdId)}/confirm`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ holdToken, idempotencyKey, ...(contact ? { contact } : {}) }) });
  const body = (await response.json()) as PublicBookingConfirmationResponse;
  if (body.data) return { kind: "ready", value: body.data };
  return { kind: response.status === 404 || response.status === 410 ? "unavailable" : "error", message: errorMessage(response.status, body.error ?? undefined) };
}
export async function fetchManagedBooking(fetcher: GuestFetcher, baseUrl: string, token: string): Promise<GuestState<NonNullable<PublicManageBookingResponse["data"]>>> { const response = await fetcher(`${baseUrl}/v1/public/manage/${encodeURIComponent(token)}`); const body = (await response.json()) as PublicManageBookingResponse; if (body.data) return { kind: "ready", value: body.data }; return { kind: response.status === 404 ? "unavailable" : "error", message: errorMessage(response.status, body.error ?? undefined) }; }
export async function rescheduleManagedBooking(fetcher: GuestFetcher, baseUrl: string, token: string, input: { startsAt: string; endsAt: string; idempotencyKey: string }): Promise<GuestState<NonNullable<PublicManageBookingResponse["data"]>>> { const response = await fetcher(`${baseUrl}/v1/public/manage/${encodeURIComponent(token)}/reschedule`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) }); const body = (await response.json()) as PublicManageBookingResponse; if (body.data) return { kind: "ready", value: body.data }; return { kind: response.status === 404 ? "unavailable" : "error", message: errorMessage(response.status, body.error ?? undefined) }; }
export async function cancelManagedBooking(fetcher: GuestFetcher, baseUrl: string, token: string, idempotencyKey: string): Promise<GuestState<NonNullable<PublicManageBookingResponse["data"]>>> { const response = await fetcher(`${baseUrl}/v1/public/manage/${encodeURIComponent(token)}/cancel`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idempotencyKey }) }); const body = (await response.json()) as PublicManageBookingResponse; if (body.data) return { kind: "ready", value: body.data }; return { kind: response.status === 404 ? "unavailable" : "error", message: errorMessage(response.status, body.error ?? undefined) }; }
