// Ownership: focused public QR conversation: discover, suggest, hold, then confirm.

import { confirmGuestHold, createGuestHold, fetchGuestAvailability, fetchGuestDestination, fetchGuestOccurrences, fetchGuestRequirementAvailability, formatRequirementAssignmentSummary, formatRequirementAvailabilityMessage, shouldFallbackToLegacyAvailability } from "./guest-booking-client.js";

const root = document.querySelector<HTMLElement>("[data-guest-booking]")!;
const intro = document.querySelector<HTMLElement>("#guest-intro")!;
const status = document.querySelector<HTMLElement>("#guest-status")!;
const form = document.querySelector<HTMLFormElement>("#guest-form")!;
const confirmPanel = document.querySelector<HTMLElement>("#guest-confirm")!;
const expiry = document.querySelector<HTMLElement>("#guest-hold-expiry")!;
const confirmButton = document.querySelector<HTMLButtonElement>("#guest-confirm-button")!;
const findSlots = document.querySelector<HTMLButtonElement>("#guest-find-slots")!;
const slotSelect = document.querySelector<HTMLSelectElement>("#guest-slot")!;
const occurrenceSelect = document.querySelector<HTMLSelectElement>("#guest-occurrence")!;
const occurrenceLabel = document.querySelector<HTMLElement>("#guest-occurrence-label")!;
const manage = document.querySelector<HTMLElement>("#guest-manage")!;
const manageLink = document.querySelector<HTMLAnchorElement>("#guest-manage-link")!;
if (!root || !intro || !status || !form || !confirmPanel || !expiry || !confirmButton || !findSlots || !slotSelect || !occurrenceSelect || !occurrenceLabel || !manage || !manageLink) throw new Error("Guest booking controls are incomplete");
const assignmentSummary = document.querySelector<HTMLElement>("#guest-assignment-summary"); const apiBase = root.dataset.apiBase || ""; const publicCode = new URLSearchParams(location.search).get("code") || ""; let serviceId: string | null = null; let hold: { holdId: string; holdToken: string } | null = null; let selectedResourceIds: readonly string[] = []; let selectedRequirementAssignments: readonly { requirementId: string; resourceIds: readonly string[]; requirementLabel?: string }[] = []; const slotResources = new Map<string, readonly string[]>(); const slotAssignments = new Map<string, readonly { requirementId: string; resourceIds: readonly string[]; requirementLabel?: string }[]>();
function show(kind: string, message: string): void { status.dataset.state = kind; status.textContent = message; status.hidden = false; }
function read(id: string): string { return document.querySelector<HTMLInputElement>(`#${id}`)?.value.trim() ?? ""; }
function localInput(iso: string): string { const date = new Date(iso); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
function clearSlots(): void { slotSelect.innerHTML = ""; slotSelect.add(new Option("Use a time above or find a suggested slot", "")); }
async function load(): Promise<void> { if (!publicCode) return show("error", "This booking link is missing its code."); const result = await fetchGuestDestination(window.fetch.bind(window), apiBase, publicCode); if (result.kind !== "ready") return show(result.kind, result.message); serviceId = result.value.serviceId; intro.textContent = serviceId ? `Choose a time for ${serviceId}.` : "Choose a service and time that works for you."; const occurrences = await fetchGuestOccurrences(window.fetch.bind(window), apiBase, publicCode); if (occurrences.kind === "ready" && occurrences.value.length) { occurrenceSelect.replaceChildren(new Option("Choose a published occurrence", "")); occurrences.value.forEach((value) => occurrenceSelect.add(new Option(`${value.label} · ${new Date(value.startsAt).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}`, `${value.id}|${value.startsAt}|${value.endsAt}|${value.serviceId}`))); occurrenceSelect.hidden = false; occurrenceLabel.hidden = false; } form.hidden = false; }
occurrenceSelect.addEventListener("change", () => { const [id, starts, ends, occurrenceService] = occurrenceSelect.value.split("|"); if (!id || !starts || !ends || !occurrenceService) return; serviceId = occurrenceService; const service = document.querySelector<HTMLInputElement>("#guest-service"); const start = document.querySelector<HTMLInputElement>("#guest-start"); const end = document.querySelector<HTMLInputElement>("#guest-end"); if (service) service.value = occurrenceService; if (start) start.value = localInput(starts); if (end) end.value = localInput(ends); });
async function findCandidateSlots(starts: Date, ends: Date, duration: number) { if (!serviceId) return fetchGuestAvailability(window.fetch.bind(window), apiBase, publicCode, { from: starts.toISOString(), to: ends.toISOString(), durationMinutes: duration, stepMinutes: duration }); const requirementResult = await fetchGuestRequirementAvailability(window.fetch.bind(window), apiBase, publicCode, { from: starts.toISOString(), to: ends.toISOString(), durationMinutes: duration, stepMinutes: duration }); if (requirementResult.kind === "ready" && shouldFallbackToLegacyAvailability(requirementResult.value)) return fetchGuestAvailability(window.fetch.bind(window), apiBase, publicCode, { from: starts.toISOString(), to: ends.toISOString(), durationMinutes: duration, stepMinutes: duration }); return requirementResult; }
findSlots.addEventListener("click", async () => { const starts = new Date(read("guest-start")); const ends = new Date(read("guest-end")); const duration = (ends.getTime() - starts.getTime()) / 60000; if (Number.isNaN(starts.getTime()) || Number.isNaN(ends.getTime()) || duration <= 0) return show("error", "Choose a valid window before finding times."); findSlots.disabled = true; show("loading", "Checking available times..."); const result = await findCandidateSlots(starts, ends, duration); findSlots.disabled = false; if (result.kind !== "ready") return show(result.kind, result.message); clearSlots(); slotResources.clear(); slotAssignments.clear(); if (assignmentSummary) assignmentSummary.hidden = true; const slots = "slots" in result.value ? result.value.slots : result.value; slots.forEach((slot) => { const key = `${slot.startsAt}|${slot.endsAt}`; const resources = "assignments" in slot ? slot.assignments.flatMap((assignment) => assignment.resourceIds) : slot.resourceIds; if ("assignments" in slot) slotAssignments.set(key, slot.assignments); slotResources.set(key, resources); slotSelect.add(new Option(`${new Date(slot.startsAt).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })} - ${new Date(slot.endsAt).toLocaleTimeString([], { timeStyle: "short" })}`, key)); }); if (!slots.length) return show("unavailable", "slots" in result.value ? formatRequirementAvailabilityMessage(result.value) : "No complete resource match is available in that window."); slotSelect.selectedIndex = 1; const firstKey = slotSelect.value; selectedResourceIds = slotResources.get(firstKey) ?? []; selectedRequirementAssignments = slotAssignments.get(firstKey) ?? []; if (assignmentSummary) { assignmentSummary.textContent = formatRequirementAssignmentSummary(selectedRequirementAssignments); assignmentSummary.hidden = !assignmentSummary.textContent; } show("ready", `${slots.length} available time${slots.length === 1 ? "" : "s"} found.`); });
slotSelect.addEventListener("change", () => { selectedResourceIds = slotResources.get(slotSelect.value) ?? []; selectedRequirementAssignments = slotAssignments.get(slotSelect.value) ?? []; if (assignmentSummary) { assignmentSummary.textContent = formatRequirementAssignmentSummary(selectedRequirementAssignments); assignmentSummary.hidden = !assignmentSummary.textContent; } const [starts, ends] = slotSelect.value.split("|"); if (starts && ends) { const startInput = document.querySelector<HTMLInputElement>("#guest-start"); const endInput = document.querySelector<HTMLInputElement>("#guest-end"); if (startInput && endInput) { startInput.value = localInput(starts); endInput.value = localInput(ends); } } });
for (const id of ["guest-start", "guest-end"]) document.querySelector<HTMLInputElement>(`#${id}`)?.addEventListener("input", () => { selectedResourceIds = []; selectedRequirementAssignments = []; slotSelect.value = ""; if (assignmentSummary) assignmentSummary.hidden = true; });
form.addEventListener("submit", async (event) => { event.preventDefault(); const starts = new Date(read("guest-start")); const ends = new Date(read("guest-end")); if (Number.isNaN(starts.getTime()) || Number.isNaN(ends.getTime()) || ends <= starts) return show("error", "Choose a valid start and end time."); show("loading", "Holding that time..."); const result = await createGuestHold(window.fetch.bind(window), apiBase, publicCode, { customerName: read("guest-name"), serviceName: read("guest-service"), startsAt: starts.toISOString(), endsAt: ends.toISOString(), idempotencyKey: crypto.randomUUID(), ...(selectedResourceIds.length ? { resourceIds: selectedResourceIds } : {}), ...(selectedRequirementAssignments.length ? { requirementAssignments: selectedRequirementAssignments } : {}) }); if (result.kind !== "ready") return show(result.kind, result.message); hold = result.value; form.hidden = true; confirmPanel.hidden = false; expiry.textContent = `This time is held until ${new Date(result.value.expiresAt).toLocaleTimeString([], { timeStyle: "short" })}.`; show("ready", "Your time is held while you review it."); });
confirmButton.addEventListener("click", async () => { if (!hold) return; const channel = (document.querySelector<HTMLSelectElement>("#guest-channel")?.value ?? "") as "email" | "sms" | "voice" | ""; const destination = read("guest-contact"); const consentGranted = document.querySelector<HTMLInputElement>("#guest-consent")?.checked === true; if (destination && !channel) return show("error", "Choose how we should contact you."); if (destination && !consentGranted) return show("error", "Please agree to reminders before adding a contact."); confirmButton.disabled = true; show("loading", "Confirming your booking..."); const contact = destination && channel ? { channel, destination, consentGranted } : undefined; const result = await confirmGuestHold(window.fetch.bind(window), apiBase, publicCode, hold.holdId, hold.holdToken, crypto.randomUUID(), contact); if (result.kind === "ready") { confirmPanel.hidden = true; manageLink.href = `./guest-manage.html?token=${encodeURIComponent(result.value.manageToken)}`; manage.hidden = false; show("ready", "Your booking is confirmed. Use the manage link if you need to change it."); } else { confirmButton.disabled = false; show(result.kind, result.message); } });
clearSlots(); void load();
