// Ownership: compact tenant pack setup; only schema-allowed overrides are submitted.

import { fetchIndustryPacks } from "./industry-packs-client.js";
import { fetchPackSelection, materializePack, savePackSelection } from "./industry-pack-settings-client.js";
const root = document.querySelector<HTMLElement>("[data-industry-pack-settings-page]"); const form = document.querySelector<HTMLFormElement>("#pack-settings-form"); const materialize = document.querySelector<HTMLButtonElement>("#materialize-pack"); const status = document.querySelector<HTMLElement>("#pack-settings-status"); const select = document.querySelector<HTMLSelectElement>("#pack-select"); const terminology = document.querySelector<HTMLInputElement>("#pack-terminology-service"); const accent = document.querySelector<HTMLInputElement>("#pack-accent");
if (!root || !form || !materialize || !status || !select || !terminology || !accent) throw new Error("Pack settings controls are incomplete");
const rootElement = root; const formElement = form; const materializeElement = materialize; const statusElement = status; const selectElement = select; const terminologyElement = terminology; const accentElement = accent; const tenantId = rootElement.dataset.tenantId || new URLSearchParams(location.search).get("tenant") || ""; const apiBase = rootElement.dataset.apiBase || "";
function show(kind: string, message: string): void { statusElement.dataset.state = kind; statusElement.textContent = message; statusElement.hidden = false; }
function readSelection(): { packId: string; packVersion: string } | null { const [packId, packVersion] = selectElement.value.split("@"); return packId && packVersion ? { packId, packVersion } : null; }
function renderPacks(packs: readonly { id: string; version: string; displayName: string }[], selected: { packId: string; packVersion: string } | null): void { selectElement.replaceChildren(); for (const pack of packs) { const option = document.createElement("option"); option.value = `${pack.id}@${pack.version}`; option.textContent = `${pack.displayName} · v${pack.version}`; option.selected = selected?.packId === pack.id && selected.packVersion === pack.version; selectElement.append(option); } }
async function load(): Promise<void> { if (!tenantId || !apiBase) return show("offline", "Connect an authorized workspace and API before changing its industry pack."); show("loading", "Loading pack settings…"); try { const [packs, selection] = await Promise.all([fetchIndustryPacks(window.fetch.bind(window), apiBase), fetchPackSelection(window.fetch.bind(window), apiBase, tenantId)]); if (packs.kind !== "ready") return show(packs.kind, packs.message); if (selection.kind === "denied") return show(selection.kind, selection.message); const selected = selection.kind === "ready" ? selection.selection : null; renderPacks(packs.packs, selected); if (selected?.overrides.terminology?.service) terminologyElement.value = selected.overrides.terminology.service; if (selected?.overrides.theme?.accent) accentElement.value = selected.overrides.theme.accent; show("ready", selected ? `${selected.packId} is selected.` : "Choose a pack for this workspace."); } catch { show("error", "Pack settings could not be reached."); } }
formElement.addEventListener("submit", async (event) => { event.preventDefault(); if (!tenantId || !apiBase) return show("offline", "Connect an authorized workspace and API before changing its industry pack."); const selection = readSelection(); if (!selection) return show("error", "Choose a valid industry pack."); const overrides = { terminology: terminologyElement.value.trim() ? { service: terminologyElement.value.trim() } : {}, theme: accentElement.value.trim() ? { accent: accentElement.value.trim() } : {} }; const result = await savePackSelection(window.fetch.bind(window), apiBase, { tenantId, ...selection, overrides }); const message = result.kind === "ready" ? `${result.selection.packId} is now active for this workspace.` : result.kind === "empty" ? "No pack selection was saved." : result.message; show(result.kind === "empty" ? "error" : result.kind, message); });
materializeElement.addEventListener("click", async () => { if (!tenantId || !apiBase) return show("offline", "Connect an authorized workspace and API before materializing pack services."); materializeElement.disabled = true; const result = await materializePack(window.fetch.bind(window), apiBase, tenantId); show(result.kind, result.kind === "ready" ? `Materialized ${result.createdServices} service${result.createdServices === 1 ? "" : "s"}, ${result.createdVariants} variant${result.createdVariants === 1 ? "" : "s"}, and ${result.createdRequirements} requirement slots.` : result.message); materializeElement.disabled = false; });
void load();
