// Ownership: tenant-scoped pack selection client with bounded override payloads.

import type { IndustryPackSelectionResponse } from "@bookingapp/contracts";
import { userFacingMessage } from "./user-messages.js";
export type PackSettingsFetcher = (url: string, init: { credentials: "include"; method?: "PUT" | "POST"; headers?: Record<string, string>; body?: string }) => Promise<{ status: number; json(): Promise<unknown> }>;
export type PackSettingsState = { kind: "ready"; selection: NonNullable<IndustryPackSelectionResponse["data"]> } | { kind: "empty" } | { kind: "denied" | "error"; message: string };
function map(status: number, body: IndustryPackSelectionResponse): PackSettingsState { if (body.data) return { kind: "ready", selection: body.data }; if (!body.error && status === 200) return { kind: "empty" }; if (body.error?.code === "TENANT_ACCESS_DENIED") return { kind: "denied", message: userFacingMessage(status, body.error, "You do not have access to industry settings.") }; return status === 404 ? { kind: "empty" } : { kind: "error", message: userFacingMessage(status, body.error, "We could not load industry settings.") }; }
export async function fetchPackSelection(fetcher: PackSettingsFetcher, baseUrl: string, tenantId: string): Promise<PackSettingsState> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/industry-pack`, { credentials: "include" }); return map(response.status, (await response.json()) as IndustryPackSelectionResponse); }
export async function savePackSelection(fetcher: PackSettingsFetcher, baseUrl: string, input: { tenantId: string; packId: string; packVersion: string; overrides: { terminology?: Record<string, string>; theme?: { accent?: string; accentSoft?: string } } }): Promise<PackSettingsState> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(input.tenantId)}/industry-pack`, { credentials: "include", method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ packId: input.packId, packVersion: input.packVersion, overrides: input.overrides }) }); return map(response.status, (await response.json()) as IndustryPackSelectionResponse); }
export async function materializePack(fetcher: PackSettingsFetcher, baseUrl: string, tenantId: string): Promise<{ kind: "ready"; createdServices: number; createdVariants: number; createdRequirements: number } | { kind: "error"; message: string }> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/industry-pack/materialize`, { credentials: "include", method: "POST" }); const body = (await response.json()) as { data: { createdServices: number; createdVariants: number; createdRequirements: number } | null; error: { code?: string; message?: string } | null }; return body.data ? { kind: "ready", ...body.data } : { kind: "error", message: userFacingMessage(response.status, body.error, "We could not apply these industry settings.") }; }
