// Ownership: compact shared pack catalog; no tenant-specific terminology is invented here.

import { fetchIndustryPacks } from "./industry-packs-client.js";
const root = document.querySelector<HTMLElement>("[data-industry-packs-page]"); const status = document.querySelector<HTMLElement>("#packs-status"); const list = document.querySelector<HTMLElement>("#packs-list");
if (!root || !status || !list) throw new Error("Industry pack page controls are incomplete");
const rootElement = root; const statusElement = status; const listElement = list; const apiBase = rootElement.dataset.apiBase || "";
function show(kind: string, message: string): void { statusElement.dataset.state = kind; statusElement.textContent = message; statusElement.hidden = false; }
function render(packs: readonly { id: string; version: string; displayName: string; supportedLocales: readonly string[]; theme: { accent: string; accentSoft: string }; navigation: readonly { id: string; label: string; href: string }[]; dashboards: readonly { id: string; title: string; metricIds: readonly string[] }[]; resourceTypes: readonly { id: string; label: string }[]; capabilities: readonly { id: string; label: string }[]; serviceTemplates: readonly { id: string; name: string; requirements: readonly unknown[] }[] }[]): void { listElement.replaceChildren(); for (const pack of packs) { const card = document.createElement("article"); card.className = "pack-card"; card.style.setProperty("--pack-accent", pack.theme.accent); card.style.setProperty("--pack-soft", pack.theme.accentSoft); const heading = document.createElement("h2"); heading.textContent = pack.displayName; const version = document.createElement("small"); version.textContent = `${pack.id} · v${pack.version}`; const summary = document.createElement("p"); summary.textContent = `${pack.serviceTemplates.length} service template${pack.serviceTemplates.length === 1 ? "" : "s"} · ${pack.resourceTypes.length} resource type${pack.resourceTypes.length === 1 ? "" : "s"} · ${pack.capabilities.length} capabilities`; const services = document.createElement("ul"); for (const service of pack.serviceTemplates) { const item = document.createElement("li"); item.textContent = `${service.name} (${service.requirements.length} requirement slots)`; services.append(item); } const contribution = document.createElement("div"); contribution.className = "pack-contributions"; const navTitle = document.createElement("strong"); navTitle.textContent = "Workspace links"; const nav = document.createElement("ul"); for (const item of pack.navigation) { const row = document.createElement("li"); const link = document.createElement("a"); link.href = item.href; link.textContent = item.label; row.append(link); nav.append(row); } const dashboard = document.createElement("p"); dashboard.textContent = pack.dashboards.map((item) => `Dashboard: ${item.title}`).join(" · "); contribution.append(navTitle, nav, dashboard); card.append(heading, version, summary, services, contribution); listElement.append(card); } }
async function load(): Promise<void> { if (!apiBase) return show("offline", "Connect the API to inspect the available industry packs."); show("loading", "Loading industry packs…"); try { const result = await fetchIndustryPacks(window.fetch.bind(window), apiBase); if (result.kind === "ready") { render(result.packs); show("ready", `${result.packs.length} industry pack${result.packs.length === 1 ? "" : "s"} available.`); } else show(result.kind, result.message); } catch { show("error", "The industry pack catalog could not be reached."); } }
void load();
