// Ownership: typed resource inventory client. It never fabricates resource availability.

import type { AvailabilityResponse, ResourceResponse, ResourcesResponse, ResourceSummary } from "@bookingapp/contracts";
import { userFacingMessage } from "./user-messages.js";

export type ResourceFetcher = (url: string, init: { credentials: "include"; method?: "POST"; headers?: Record<string, string>; body?: string }) => Promise<{ status: number; json(): Promise<unknown> }>;
export type ResourcesState = { kind: "ready"; resources: readonly ResourceSummary[] } | { kind: "denied" | "error"; message: string };
export type AvailabilityState = { kind: "ready"; slots: NonNullable<AvailabilityResponse["data"]> } | { kind: "denied" | "error"; message: string };
function map(status: number, body: ResourcesResponse): ResourcesState { if (body.data) return { kind: "ready", resources: body.data }; if (body.error?.code === "TENANT_ACCESS_DENIED" || body.error?.code === "UNAUTHENTICATED") return { kind: "denied", message: userFacingMessage(status, body.error, "You do not have access to resources.") }; return { kind: "error", message: userFacingMessage(status, body.error, "We could not load resources.") }; }
export async function fetchResources(fetcher: ResourceFetcher, baseUrl: string, tenantId: string): Promise<ResourcesState> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/resources`, { credentials: "include" }); return map(response.status, (await response.json()) as ResourcesResponse); }
export async function createResource(fetcher: ResourceFetcher, baseUrl: string, tenantId: string, input: { name: string; resourceType: string; capabilities?: readonly string[] }): Promise<{ kind: "ready"; resource: NonNullable<ResourceResponse["data"]> } | { kind: "error"; message: string }> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/resources`, { credentials: "include", method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) }); const body = (await response.json()) as ResourceResponse; return body.data ? { kind: "ready", resource: body.data } : { kind: "error", message: userFacingMessage(response.status, body.error, "We could not create that resource.") }; }
export async function setResourceStatus(fetcher: ResourceFetcher, baseUrl: string, tenantId: string, resourceId: string, status: "active" | "inactive"): Promise<{ kind: "ready" } | { kind: "error"; message: string }> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/resources/${encodeURIComponent(resourceId)}/status`, { credentials: "include", method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); const body = (await response.json()) as { data: unknown; error: { code?: string; message?: string } | null }; return body.data ? { kind: "ready" } : { kind: "error", message: userFacingMessage(response.status, body.error, "We could not update that resource.") }; }
export async function fetchResourceAvailability(fetcher: ResourceFetcher, baseUrl: string, tenantId: string, input: { from: string; to: string; durationMinutes: number; stepMinutes?: number; requiredResourceCount?: number }): Promise<AvailabilityState> { const query = new URLSearchParams({ from: input.from, to: input.to, durationMinutes: String(input.durationMinutes), stepMinutes: String(input.stepMinutes ?? input.durationMinutes), requiredResourceCount: String(input.requiredResourceCount ?? 1) }); const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/availability?${query}`, { credentials: "include" }); const body = (await response.json()) as AvailabilityResponse; if (body.data) return { kind: "ready", slots: body.data }; if (body.error?.code === "TENANT_ACCESS_DENIED") return { kind: "denied", message: userFacingMessage(response.status, body.error, "You do not have access to availability.") }; return { kind: "error", message: userFacingMessage(response.status, body.error, "We could not load availability.") }; }
