// Ownership: typed service catalog client; it never invents service rows.

import type { ServiceResponse, ServicesResponse } from "@bookingapp/contracts";
import { userFacingMessage } from "./user-messages.js";
export type ServiceFetcher = (url: string, init: { credentials: "include"; method?: "POST"; headers?: Record<string, string>; body?: string }) => Promise<{ status: number; json(): Promise<unknown> }>;
export type ServicesState = { kind: "ready"; services: readonly NonNullable<ServicesResponse["data"]>[number][] } | { kind: "denied" | "error"; message: string };
function map(status: number, body: ServicesResponse): ServicesState { if (body.data) return { kind: "ready", services: body.data }; if (body.error?.code === "TENANT_ACCESS_DENIED" || body.error?.code === "UNAUTHENTICATED") return { kind: "denied", message: userFacingMessage(status, body.error, "You do not have access to services.") }; return { kind: "error", message: userFacingMessage(status, body.error, "We could not load services.") }; }
export async function fetchServices(fetcher: ServiceFetcher, baseUrl: string, tenantId: string): Promise<ServicesState> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/services`, { credentials: "include" }); return map(response.status, (await response.json()) as ServicesResponse); }
export async function createService(fetcher: ServiceFetcher, baseUrl: string, tenantId: string, input: { name: string; description?: string | null; bookingMode: "appointment" | "occurrence"; durationMinutes: number; bufferBeforeMinutes?: number; bufferAfterMinutes?: number; priceCents?: number | null; currency?: string | null; packId?: string | null }): Promise<{ kind: "ready"; service: NonNullable<ServiceResponse["data"]> } | { kind: "error"; message: string }> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/services`, { credentials: "include", method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) }); const body = (await response.json()) as ServiceResponse; return body.data ? { kind: "ready", service: body.data } : { kind: "error", message: userFacingMessage(response.status, body.error, "We could not create that service.") }; }
export async function setServiceStatus(fetcher: ServiceFetcher, baseUrl: string, tenantId: string, serviceId: string, status: "active" | "inactive"): Promise<{ kind: "ready" } | { kind: "error"; message: string }> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/services/${encodeURIComponent(serviceId)}/status`, { credentials: "include", method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); const body = (await response.json()) as ServiceResponse; return body.data ? { kind: "ready" } : { kind: "error", message: userFacingMessage(response.status, body.error, "We could not update that service.") }; }
