// Ownership: typed client for service variants and requirement slots.

import type { ServiceRequirementResponse, ServiceRequirementsResponse, ServiceVariantResponse, ServiceVariantsResponse } from "@bookingapp/contracts";
import type { ServiceFetcher } from "./services-client.js";
import { userFacingMessage } from "./user-messages.js";

export type CompositionState<T> = { kind: "ready"; data: T } | { kind: "denied" | "error"; message: string };
function map<T>(status: number, body: { data: T | null; error: { code?: string; message: string } | null }, unavailable: string): CompositionState<T> { if (body.data !== null) return { kind: "ready", data: body.data }; if (body.error?.code === "TENANT_ACCESS_DENIED" || body.error?.code === "UNAUTHENTICATED") return { kind: "denied", message: userFacingMessage(status, body.error, "You do not have access to service setup.") }; return { kind: "error", message: userFacingMessage(status, body.error, `We could not load ${unavailable.toLowerCase()}.`) }; }
export async function fetchVariants(fetcher: ServiceFetcher, baseUrl: string, tenantId: string, serviceId: string): Promise<CompositionState<NonNullable<ServiceVariantsResponse["data"]>>> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/services/${encodeURIComponent(serviceId)}/variants`, { credentials: "include" }); return map(response.status, (await response.json()) as ServiceVariantsResponse, "Variants"); }
export async function createVariant(fetcher: ServiceFetcher, baseUrl: string, tenantId: string, serviceId: string, input: { name: string; durationMinutes?: number | null; bufferBeforeMinutes?: number | null; bufferAfterMinutes?: number | null }): Promise<CompositionState<NonNullable<ServiceVariantResponse["data"]>>> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/services/${encodeURIComponent(serviceId)}/variants`, { credentials: "include", method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) }); return map(response.status, (await response.json()) as ServiceVariantResponse, "Variant"); }
export async function setVariantStatus(fetcher: ServiceFetcher, baseUrl: string, tenantId: string, variantId: string, status: "active" | "inactive"): Promise<CompositionState<{ variantId: string; status: string }>> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/service-variants/${encodeURIComponent(variantId)}/status`, { credentials: "include", method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); return map(response.status, (await response.json()) as { data: { variantId: string; status: string } | null; error: { code?: string; message: string } | null }, "Variant status"); }
export async function fetchRequirements(fetcher: ServiceFetcher, baseUrl: string, tenantId: string, serviceId: string, variantId?: string): Promise<CompositionState<NonNullable<ServiceRequirementsResponse["data"]>>> { const query = variantId ? `?variantId=${encodeURIComponent(variantId)}` : ""; const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/services/${encodeURIComponent(serviceId)}/requirements${query}`, { credentials: "include" }); return map(response.status, (await response.json()) as ServiceRequirementsResponse, "Requirements"); }
export async function createRequirement(fetcher: ServiceFetcher, baseUrl: string, tenantId: string, serviceId: string, input: { variantId?: string | null; kind: "resource"; label: string; quantity?: number; resourceType?: string | null; capabilityKey?: string | null }): Promise<CompositionState<NonNullable<ServiceRequirementResponse["data"]>>> { const response = await fetcher(`${baseUrl}/v1/tenants/${encodeURIComponent(tenantId)}/services/${encodeURIComponent(serviceId)}/requirements`, { credentials: "include", method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) }); return map(response.status, (await response.json()) as ServiceRequirementResponse, "Requirement"); }
