// Ownership: compact service catalog workspace backed by the authorized API.

import { createService, fetchServices, setServiceStatus } from "./services-client.js";
const root = document.querySelector<HTMLElement>("[data-services-page]"); const form = document.querySelector<HTMLFormElement>("#service-form"); const status = document.querySelector<HTMLElement>("#service-status"); const list = document.querySelector<HTMLElement>("#service-list"); const refresh = document.querySelector<HTMLButtonElement>("#refresh-services");
if (!root || !form || !status || !list || !refresh) throw new Error("Service workspace controls are incomplete");
const rootElement = root; const formElement = form; const statusElement = status; const listElement = list; const refreshElement = refresh;
const tenantId = rootElement.dataset.tenantId || new URLSearchParams(location.search).get("tenant") || ""; const apiBase = rootElement.dataset.apiBase || "";
function show(kind: string, message: string): void { statusElement.dataset.state = kind; statusElement.textContent = message; statusElement.hidden = false; }
function render(services: readonly { id: string; name: string; description: string | null; bookingMode: "appointment" | "occurrence"; durationMinutes: number; bufferBeforeMinutes: number; bufferAfterMinutes: number; status: "active" | "inactive" }[]): void { listElement.replaceChildren(); if (!services.length) { listElement.textContent = "No services configured for this workspace."; return; } for (const service of services) { const row = document.createElement("article"); row.className = "service-row"; const heading = document.createElement("strong"); heading.textContent = service.name; const meta = document.createElement("span"); meta.textContent = `${service.bookingMode} · ${service.durationMinutes} min${service.bufferBeforeMinutes + service.bufferAfterMinutes ? ` · buffers ${service.bufferBeforeMinutes + service.bufferAfterMinutes} min` : ""}`; const description = document.createElement("small"); description.textContent = service.description || "No description"; const state = document.createElement("small"); state.className = `service-status service-status-${service.status}`; state.textContent = service.status; const configure = document.createElement("a"); configure.className = "account-button"; configure.href = `./service-composition.html?service=${encodeURIComponent(service.id)}${tenantId ? `&tenant=${encodeURIComponent(tenantId)}` : ""}`; configure.textContent = "Configure variants"; const button = document.createElement("button"); button.type = "button"; button.className = "account-button"; button.textContent = service.status === "active" ? "Pause" : "Activate"; button.addEventListener("click", async () => { button.disabled = true; const next = service.status === "active" ? "inactive" : "active"; const result = await setServiceStatus(window.fetch.bind(window), apiBase, tenantId, service.id, next); if (result.kind === "ready") { show("ready", `${service.name} is now ${next}.`); await load(); } else show("error", result.message); button.disabled = false; }); row.append(heading, state, meta, description, configure, button); listElement.append(row); } }
async function load(): Promise<void> { if (!tenantId) return show("denied", "Choose an authorized workspace before managing services."); show("loading", "Loading services…"); const result = await fetchServices(window.fetch.bind(window), apiBase, tenantId); if (result.kind === "ready") { render(result.services); show("ready", `${result.services.length} service${result.services.length === 1 ? "" : "s"} loaded.`); } else show(result.kind, result.message); }
formElement.addEventListener("submit", async (event) => { event.preventDefault(); if (!tenantId) return show("denied", "Choose an authorized workspace before creating a service."); const read = (id: string): string => document.querySelector<HTMLInputElement>(`#${id}`)?.value.trim() ?? ""; const durationMinutes = Number(read("service-duration")); const input = { name: read("service-name"), description: read("service-description") || null, bookingMode: (document.querySelector<HTMLSelectElement>("#service-mode")?.value ?? "appointment") as "appointment" | "occurrence", durationMinutes, bufferBeforeMinutes: Number(read("service-buffer-before") || 0), bufferAfterMinutes: Number(read("service-buffer-after") || 0) }; if (!input.name || !Number.isInteger(durationMinutes)) return show("error", "Enter a service name and whole-minute duration."); const result = await createService(window.fetch.bind(window), apiBase, tenantId, input); if (result.kind === "ready") { formElement.reset(); show("ready", `${result.service.name} was added.`); await load(); } else show("error", result.message); });
refreshElement.addEventListener("click", () => { void load(); }); void load();
