// Ownership: tenant-authorized pack selection and bounded override routes.

import type { FastifyInstance, FastifyRequest } from "fastify";
import type { IndustryPackOverrides, IndustryPackSelection } from "@bookingapp/domain";
import type { TenantContextRequest } from "./tenant-context-handler.js";
interface PackInput { packId: string; packVersion: string; overrides?: IndustryPackOverrides; }
export interface IndustryPackSettingsRouteDependencies { resolve(request: FastifyRequest<{ Params: { tenantId: string } }>): TenantContextRequest | Promise<TenantContextRequest>; packAdmin: { read(tenantId: string): Promise<IndustryPackSelection | null>; save(input: IndustryPackSelection, actorId: string | null): Promise<IndustryPackSelection>; materialize?(tenantId: string, actorId: string | null): Promise<unknown>; } | undefined; }
function allowed(context: TenantContextRequest, tenantId: string, roles: readonly string[]): boolean { return Boolean(context.identity && context.membership && context.membership.tenantId === tenantId && roles.includes(context.membership.role)); }
function denied(reply: { code(code: number): { send(payload: unknown): unknown } }): unknown { return reply.code(403).send({ data: null, error: { code: "TENANT_ACCESS_DENIED", message: "You do not have access to this workspace." } }); }
export function registerIndustryPackSettingsRoutes(app: FastifyInstance, dependencies: IndustryPackSettingsRouteDependencies): void { app.get<{ Params: { tenantId: string } }>("/v1/tenants/:tenantId/industry-pack", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId, ["owner", "admin", "manager"])) return denied(reply); if (!dependencies.packAdmin) return reply.code(503).send({ data: null, error: { code: "PACK_SETTINGS_UNAVAILABLE", message: "Pack settings are temporarily unavailable." } }); return reply.send({ data: await dependencies.packAdmin.read(request.params.tenantId), error: null }); }); app.put<{ Params: { tenantId: string }; Body: PackInput }>("/v1/tenants/:tenantId/industry-pack", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId, ["owner", "admin"])) return denied(reply); if (!dependencies.packAdmin) return reply.code(503).send({ data: null, error: { code: "PACK_SETTINGS_UNAVAILABLE", message: "Pack settings are temporarily unavailable." } }); const body = request.body; if (!body?.packId?.trim() || !body.packVersion?.trim()) return reply.code(400).send({ data: null, error: { code: "PACK_INVALID", message: "Pack id and version are required." } }); try { return reply.send({ data: await dependencies.packAdmin.save({ tenantId: request.params.tenantId, packId: body.packId.trim(), packVersion: body.packVersion.trim(), overrides: body.overrides ?? {} }, context.mappedUserId), error: null }); } catch (error) { return reply.code(400).send({ data: null, error: { code: "PACK_INVALID", message: error instanceof Error ? error.message : "Pack selection is invalid." } }); } }); app.post<{ Params: { tenantId: string } }>("/v1/tenants/:tenantId/industry-pack/materialize", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId, ["owner", "admin"])) return denied(reply); if (!dependencies.packAdmin?.materialize) return reply.code(503).send({ data: null, error: { code: "PACK_SETTINGS_UNAVAILABLE", message: "Pack materialization is temporarily unavailable." } }); try { return reply.code(201).send({ data: await dependencies.packAdmin.materialize(request.params.tenantId, context.mappedUserId), error: null }); } catch (error) { return reply.code(400).send({ data: null, error: { code: "PACK_INVALID", message: error instanceof Error ? error.message : "Pack services could not be materialized." } }); } }); }
