// Ownership: authorized tenant service catalog routes; service feasibility stays in domain/persistence.

import type { FastifyInstance, FastifyRequest } from "fastify";
import { randomUUID } from "node:crypto";
import type { ServiceBookingMode } from "@bookingapp/domain";
import type { TenantContextRequest } from "./tenant-context-handler.js";

interface ServiceInput { name: string; description?: string | null; bookingMode: ServiceBookingMode; durationMinutes: number; bufferBeforeMinutes?: number; bufferAfterMinutes?: number; priceCents?: number | null; currency?: string | null; packId?: string | null; }
export interface ServiceRouteDependencies { resolve(request: FastifyRequest<{ Params: { tenantId: string } }>): TenantContextRequest | Promise<TenantContextRequest>; serviceAdmin: { list(tenantId: string): Promise<readonly unknown[]>; create(input: ServiceInput & { id: string; tenantId: string }): Promise<unknown>; setStatus(tenantId: string, serviceId: string, status: "active" | "inactive"): Promise<boolean>; } | undefined; }
function allowed(context: TenantContextRequest, tenantId: string, roles = ["owner", "admin", "manager"]): boolean { return Boolean(context.identity && context.membership && context.membership.tenantId === tenantId && roles.includes(context.membership.role)); }
function denied(reply: { code(code: number): { send(payload: unknown): unknown } }): unknown { return reply.code(403).send({ data: null, error: { code: "TENANT_ACCESS_DENIED", message: "You do not have access to this workspace." } }); }
export function registerServiceRoutes(app: FastifyInstance, dependencies: ServiceRouteDependencies): void {
  app.get<{ Params: { tenantId: string } }>("/v1/tenants/:tenantId/services", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId)) return denied(reply); if (!dependencies.serviceAdmin) return reply.code(503).send({ data: null, error: { code: "SERVICES_UNAVAILABLE", message: "Services are temporarily unavailable." } }); return reply.send({ data: await dependencies.serviceAdmin.list(request.params.tenantId), error: null }); });
  app.post<{ Params: { tenantId: string }; Body: ServiceInput }>("/v1/tenants/:tenantId/services", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId, ["owner", "admin"])) return denied(reply); if (!dependencies.serviceAdmin) return reply.code(503).send({ data: null, error: { code: "SERVICES_UNAVAILABLE", message: "Services are temporarily unavailable." } }); const body = request.body; if (!body?.name?.trim() || !["appointment", "occurrence"].includes(body.bookingMode) || !Number.isInteger(body.durationMinutes)) return reply.code(400).send({ data: null, error: { code: "SERVICE_INVALID", message: "Service name, mode, and duration are required." } }); try { return reply.code(201).send({ data: await dependencies.serviceAdmin.create({ ...body, id: randomUUID(), tenantId: request.params.tenantId, name: body.name.trim() }), error: null }); } catch (error) { return reply.code(400).send({ data: null, error: { code: "SERVICE_INVALID", message: error instanceof Error ? error.message : "Service could not be created." } }); } });
  app.post<{ Params: { tenantId: string; serviceId: string }; Body: { status: "active" | "inactive" } }>("/v1/tenants/:tenantId/services/:serviceId/status", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId, ["owner", "admin"])) return denied(reply); if (!dependencies.serviceAdmin) return reply.code(503).send({ data: null, error: { code: "SERVICES_UNAVAILABLE", message: "Services are temporarily unavailable." } }); if (request.body?.status !== "active" && request.body?.status !== "inactive") return reply.code(400).send({ data: null, error: { code: "SERVICE_INVALID", message: "Service status is invalid." } }); const changed = await dependencies.serviceAdmin.setStatus(request.params.tenantId, request.params.serviceId, request.body.status); return changed ? reply.send({ data: { serviceId: request.params.serviceId, status: request.body.status }, error: null }) : reply.code(404).send({ data: null, error: { code: "SERVICE_NOT_FOUND", message: "Service was not found." } }); });
}
