// Ownership: authorized service variant and requirement configuration routes.

import type { FastifyInstance, FastifyRequest } from "fastify";
import { randomUUID } from "node:crypto";
import type { ServiceRequirementKind, ServiceVariantStatus } from "@bookingapp/domain";
import type { TenantContextRequest } from "./tenant-context-handler.js";

interface VariantInput { name: string; durationMinutes?: number | null; bufferBeforeMinutes?: number | null; bufferAfterMinutes?: number | null; priceCents?: number | null; currency?: string | null; }
interface RequirementInput { variantId?: string | null; kind: ServiceRequirementKind; label: string; quantity?: number; resourceType?: string | null; capabilityKey?: string | null; }
export interface ServiceCompositionRouteDependencies { resolve(request: FastifyRequest<{ Params: { tenantId: string } }>): TenantContextRequest | Promise<TenantContextRequest>; compositionAdmin: { listVariants(tenantId: string, serviceId: string): Promise<readonly unknown[]>; createVariant(input: VariantInput & { id: string; tenantId: string; serviceId: string }): Promise<unknown>; setVariantStatus(tenantId: string, variantId: string, status: ServiceVariantStatus): Promise<boolean>; listRequirements(tenantId: string, serviceId: string, variantId?: string | null): Promise<readonly unknown[]>; createRequirement(input: RequirementInput & { id: string; tenantId: string; serviceId: string }): Promise<unknown>; setRequirementStatus(tenantId: string, requirementId: string, status: ServiceVariantStatus): Promise<boolean>; } | undefined; }
function allowed(context: TenantContextRequest, tenantId: string, roles = ["owner", "admin", "manager"]): boolean { return Boolean(context.identity && context.membership && context.membership.tenantId === tenantId && roles.includes(context.membership.role)); }
function denied(reply: { code(code: number): { send(payload: unknown): unknown } }): unknown { return reply.code(403).send({ data: null, error: { code: "TENANT_ACCESS_DENIED", message: "You do not have access to this workspace." } }); }
export function registerServiceCompositionRoutes(app: FastifyInstance, dependencies: ServiceCompositionRouteDependencies): void {
  app.get<{ Params: { tenantId: string; serviceId: string } }>("/v1/tenants/:tenantId/services/:serviceId/variants", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId)) return denied(reply); if (!dependencies.compositionAdmin) return reply.code(503).send({ data: null, error: { code: "SERVICE_VARIANTS_UNAVAILABLE", message: "Service variants are temporarily unavailable." } }); return reply.send({ data: await dependencies.compositionAdmin.listVariants(request.params.tenantId, request.params.serviceId), error: null }); });
  app.post<{ Params: { tenantId: string; serviceId: string }; Body: VariantInput }>("/v1/tenants/:tenantId/services/:serviceId/variants", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId, ["owner", "admin"])) return denied(reply); if (!dependencies.compositionAdmin) return reply.code(503).send({ data: null, error: { code: "SERVICE_VARIANTS_UNAVAILABLE", message: "Service variants are temporarily unavailable." } }); if (!request.body?.name?.trim()) return reply.code(400).send({ data: null, error: { code: "SERVICE_INVALID", message: "Variant name is required." } }); try { return reply.code(201).send({ data: await dependencies.compositionAdmin.createVariant({ ...request.body, id: randomUUID(), tenantId: request.params.tenantId, serviceId: request.params.serviceId, name: request.body.name.trim() }), error: null }); } catch (error) { return reply.code(400).send({ data: null, error: { code: "SERVICE_INVALID", message: error instanceof Error ? error.message : "Variant could not be created." } }); } });
  app.post<{ Params: { tenantId: string; variantId: string }; Body: { status: ServiceVariantStatus } }>("/v1/tenants/:tenantId/service-variants/:variantId/status", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId, ["owner", "admin"])) return denied(reply); if (!dependencies.compositionAdmin) return reply.code(503).send({ data: null, error: { code: "SERVICE_VARIANTS_UNAVAILABLE", message: "Service variants are temporarily unavailable." } }); if (request.body?.status !== "active" && request.body?.status !== "inactive") return reply.code(400).send({ data: null, error: { code: "SERVICE_INVALID", message: "Variant status is invalid." } }); const changed = await dependencies.compositionAdmin.setVariantStatus(request.params.tenantId, request.params.variantId, request.body.status); return changed ? reply.send({ data: { variantId: request.params.variantId, status: request.body.status }, error: null }) : reply.code(404).send({ data: null, error: { code: "SERVICE_VARIANT_NOT_FOUND", message: "The service variant was not found." } }); });
  app.get<{ Params: { tenantId: string; serviceId: string }; Querystring: { variantId?: string } }>("/v1/tenants/:tenantId/services/:serviceId/requirements", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId)) return denied(reply); if (!dependencies.compositionAdmin) return reply.code(503).send({ data: null, error: { code: "SERVICE_REQUIREMENTS_UNAVAILABLE", message: "Service requirements are temporarily unavailable." } }); return reply.send({ data: await dependencies.compositionAdmin.listRequirements(request.params.tenantId, request.params.serviceId, request.query.variantId), error: null }); });
  app.post<{ Params: { tenantId: string; serviceId: string }; Body: RequirementInput }>("/v1/tenants/:tenantId/services/:serviceId/requirements", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId, ["owner", "admin"])) return denied(reply); if (!dependencies.compositionAdmin) return reply.code(503).send({ data: null, error: { code: "SERVICE_REQUIREMENTS_UNAVAILABLE", message: "Service requirements are temporarily unavailable." } }); if (!request.body?.label?.trim() || request.body.kind !== "resource") return reply.code(400).send({ data: null, error: { code: "SERVICE_INVALID", message: "Requirement kind and label are required." } }); try { return reply.code(201).send({ data: await dependencies.compositionAdmin.createRequirement({ ...request.body, id: randomUUID(), tenantId: request.params.tenantId, serviceId: request.params.serviceId, label: request.body.label.trim() }), error: null }); } catch (error) { return reply.code(400).send({ data: null, error: { code: "SERVICE_INVALID", message: error instanceof Error ? error.message : "Requirement could not be created." } }); } });
  app.post<{ Params: { tenantId: string; requirementId: string }; Body: { status: ServiceVariantStatus } }>("/v1/tenants/:tenantId/service-requirements/:requirementId/status", async (request, reply) => { const context = await dependencies.resolve(request); if (!allowed(context, request.params.tenantId, ["owner", "admin"])) return denied(reply); if (!dependencies.compositionAdmin) return reply.code(503).send({ data: null, error: { code: "SERVICE_REQUIREMENTS_UNAVAILABLE", message: "Service requirements are temporarily unavailable." } }); if (request.body?.status !== "active" && request.body?.status !== "inactive") return reply.code(400).send({ data: null, error: { code: "SERVICE_INVALID", message: "Requirement status is invalid." } }); const changed = await dependencies.compositionAdmin.setRequirementStatus(request.params.tenantId, request.params.requirementId, request.body.status); return changed ? reply.send({ data: { requirementId: request.params.requirementId, status: request.body.status }, error: null }) : reply.code(404).send({ data: null, error: { code: "SERVICE_REQUIREMENT_NOT_FOUND", message: "The service requirement was not found." } }); });
}
