import assert from "node:assert/strict";
import test from "node:test";
import { createApiServer } from "./server.js";

const identity = { issuer: "https://novaauth.niuautomations.com", subject: "sub-1" };
const membership = { userId: "user-1", tenantId: "tenant-1", branchIds: [], role: "owner", status: "active" as const };
const resolve = (request: { params: { tenantId: string } }) => ({ identity, mappedUserId: "user-1", membership, requestedTenantId: request.params.tenantId });
const serviceAdmin = { list: async () => [{ id: "svc-1", name: "Consultation" }], create: async (input: unknown) => input, setStatus: async () => true };
const compositionAdmin = { listVariants: async () => [{ id: "variant-1", name: "Manual" }], createVariant: async (input: unknown) => input, setVariantStatus: async () => true, listRequirements: async () => [{ id: "requirement-1", label: "Instructor" }], createRequirement: async (input: unknown) => input, setRequirementStatus: async () => true };
const packAdmin = { read: async () => ({ tenantId: "tenant-1", packId: "driving-school", packVersion: "1.0.0", overrides: {} }), save: async (input: import("@bookingapp/domain").IndustryPackSelection) => input, materialize: async () => ({ tenantId: "tenant-1", packId: "driving-school", packVersion: "1.0.0", createdServices: 1, createdVariants: 1, createdRequirements: 2 }) };
test("lists, creates, and changes tenant services through HTTP", async () => { const app = createApiServer({ resolve, serviceAdmin }); assert.equal((await app.inject({ method: "GET", url: "/v1/tenants/tenant-1/services" })).statusCode, 200); const created = await app.inject({ method: "POST", url: "/v1/tenants/tenant-1/services", payload: { name: "Consultation", bookingMode: "appointment", durationMinutes: 30 } }); assert.equal(created.statusCode, 201); const changed = await app.inject({ method: "POST", url: "/v1/tenants/tenant-1/services/svc-1/status", payload: { status: "inactive" } }); assert.equal(changed.statusCode, 200); await app.close(); });
test("rejects malformed service input", async () => { const app = createApiServer({ resolve, serviceAdmin }); const response = await app.inject({ method: "POST", url: "/v1/tenants/tenant-1/services", payload: { name: "", bookingMode: "appointment", durationMinutes: 30 } }); assert.equal(response.statusCode, 400); await app.close(); });
test("configures service variants and requirement slots", async () => { const app = createApiServer({ resolve, serviceAdmin, compositionAdmin }); assert.equal((await app.inject({ method: "GET", url: "/v1/tenants/tenant-1/services/svc-1/variants" })).statusCode, 200); assert.equal((await app.inject({ method: "POST", url: "/v1/tenants/tenant-1/services/svc-1/variants", payload: { name: "Manual" } })).statusCode, 201); assert.equal((await app.inject({ method: "GET", url: "/v1/tenants/tenant-1/services/svc-1/requirements" })).statusCode, 200); assert.equal((await app.inject({ method: "POST", url: "/v1/tenants/tenant-1/services/svc-1/requirements", payload: { kind: "resource", label: "Instructor", capabilityKey: "licence.manual" } })).statusCode, 201); await app.close(); });
test("exposes the code-reviewed industry pack catalog and UI contributions", async () => { const app = createApiServer({ resolve }); const response = await app.inject({ method: "GET", url: "/v1/industry-packs" }); assert.equal(response.statusCode, 200); assert.match(response.body, /Driving School/iu); assert.match(response.body, /Lessons/iu); assert.match(response.body, /Lesson progress/iu); await app.close(); });
test("reads and updates a tenant industry pack selection", async () => { const app = createApiServer({ resolve, packAdmin }); assert.equal((await app.inject({ method: "GET", url: "/v1/tenants/tenant-1/industry-pack" })).statusCode, 200); const response = await app.inject({ method: "PUT", url: "/v1/tenants/tenant-1/industry-pack", payload: { packId: "driving-school", packVersion: "1.0.0", overrides: { terminology: { service: "Lesson" } } } }); assert.equal(response.statusCode, 200); await app.close(); });
test("materializes a selected pack through an authorized command", async () => { const app = createApiServer({ resolve, packAdmin }); const response = await app.inject({ method: "POST", url: "/v1/tenants/tenant-1/industry-pack/materialize" }); assert.equal(response.statusCode, 201); await app.close(); });
