// Ownership: tenant-scoped industry pack selection and bounded overrides.
"use client";

import { useEffect, useState } from "react";
import type { IndustryPackManifest } from "@bookingapp/domain";
import { fetchIndustryPacks } from "../../src/industry-packs-client.js";
import { fetchPackSelection, materializePack, savePackSelection } from "../../src/industry-pack-settings-client.js";
import { AdmissionNotice, apiBase, useWorkspaceAdmission, WorkspacePicker } from "./workspace-admission.js";
import { WorkspaceShell } from "./workspace-shell.js";

type RequestInitLike = { credentials: "include"; method?: "PUT" | "POST"; headers?: Record<string, string>; body?: string };
type PackSummary = Pick<IndustryPackManifest, "id" | "version" | "displayName" | "theme" | "serviceTemplates" | "resourceTypes" | "capabilities">;
const request = (input: string, init: RequestInitLike) => window.fetch(input, init);

export function PackSettingsPage() {
  const { admission } = useWorkspaceAdmission();
  const [packs, setPacks] = useState<readonly PackSummary[]>([]);
  const [selected, setSelected] = useState("");
  const [serviceLabel, setServiceLabel] = useState("");
  const [accent, setAccent] = useState("");
  const [status, setStatus] = useState<{ kind: "loading" | "ready" | "error"; message: string } | null>(null);
  const [saving, setSaving] = useState(false);
  const [materializing, setMaterializing] = useState(false);
  const selectedPack = packs.find((pack) => `${pack.id}@${pack.version}` === selected);
  const busy = saving || materializing;
  const load = () => { if (admission.kind !== "ready") return; setStatus({ kind: "loading", message: "Loading industry pack settings..." }); void Promise.all([fetchIndustryPacks(request, apiBase), fetchPackSelection(request, apiBase, admission.tenantId)]).then(([catalog, selection]) => { if (catalog.kind !== "ready") return setStatus({ kind: "error", message: catalog.message }); setPacks(catalog.packs); const current = selection.kind === "ready" ? selection.selection : null; const key = current ? `${current.packId}@${current.packVersion}` : `${catalog.packs[0]?.id ?? ""}@${catalog.packs[0]?.version ?? ""}`; setSelected(key); setServiceLabel(current?.overrides.terminology?.service ?? ""); setAccent(current?.overrides.theme?.accent ?? ""); setStatus({ kind: "ready", message: current ? `${current.packId} is selected.` : "Choose a pack for this workspace." }); }).catch(() => setStatus({ kind: "error", message: "Industry pack settings could not be loaded." })); };
  useEffect(load, [admission]);
  async function save() { if (admission.kind !== "ready" || !selectedPack || busy) return; const [packId, packVersion] = selected.split("@"); if (!packId || !packVersion) return setStatus({ kind: "error", message: "Choose a valid industry pack." }); if (accent && !/^#[0-9a-f]{6}$/iu.test(accent)) return setStatus({ kind: "error", message: "Accent must be a six-digit hex color such as #3730A3." }); setSaving(true); setStatus({ kind: "loading", message: "Saving workspace pack..." }); try { const result = await savePackSelection(request, apiBase, { tenantId: admission.tenantId, packId, packVersion, overrides: { terminology: serviceLabel.trim() ? { service: serviceLabel.trim() } : {}, theme: accent.trim() ? { accent: accent.trim() } : {} } }); setStatus(result.kind === "ready" ? { kind: "ready", message: `${result.selection.packId} is now active for this workspace.` } : { kind: "error", message: result.kind === "empty" ? "No pack selection was saved." : result.message }); } catch { setStatus({ kind: "error", message: "Workspace pack could not be saved." }); } finally { setSaving(false); } }
  async function materialize() { if (admission.kind !== "ready" || busy) return; setMaterializing(true); setStatus({ kind: "loading", message: "Materializing pack services..." }); try { const result = await materializePack(request, apiBase, admission.tenantId); setStatus(result.kind === "ready" ? { kind: "ready", message: `Materialized ${result.createdServices} service${result.createdServices === 1 ? "" : "s"}, ${result.createdVariants} variant${result.createdVariants === 1 ? "" : "s"}, and ${result.createdRequirements} requirement slots.` } : { kind: "error", message: result.message }); } catch { setStatus({ kind: "error", message: "Pack services could not be materialized." }); } finally { setMaterializing(false); } }
  return <WorkspaceShell activeHref="/app/pack-settings"><section className="workspace-content pack-settings-page"><header className="page-intro"><div><p className="eyebrow">Workspace configuration</p><h1>Pack settings</h1><p className="intro-copy">Choose operational vocabulary and a restrained accent for this organization.</p></div><div className="pack-settings-header-actions"><a className="account-button" href="/app/packs">Browse packs</a><button className="account-button" type="button" onClick={() => void load()} disabled={busy}>Refresh</button></div></header>{admission.kind === "selecting" ? <WorkspacePicker workspaces={admission.workspaces} title="Choose a workspace for pack settings" /> : admission.kind !== "ready" ? <AdmissionNotice state={admission} title="Choose a workspace to configure its industry pack" /> : <>{status && <p className={`pack-settings-status ${status.kind}`} role="status">{status.message}</p>}<article className="pack-settings-card"><div className="pack-settings-form"><label>Active pack<select value={selected} disabled={busy} onChange={(event) => { setSelected(event.target.value); setServiceLabel(""); setAccent(""); }}>{packs.map((pack) => <option key={`${pack.id}@${pack.version}`} value={`${pack.id}@${pack.version}`}>{pack.displayName} · v{pack.version}</option>)}</select></label><label>Service label override <span className="field-optional">optional</span><input maxLength={120} placeholder="Service" value={serviceLabel} disabled={busy} onChange={(event) => setServiceLabel(event.target.value)} /></label><label>Accent override <span className="field-optional">optional</span><input pattern="^#[0-9a-fA-F]{6}$" placeholder={selectedPack?.theme.accent ?? "#3730A3"} value={accent} disabled={busy} onChange={(event) => setAccent(event.target.value)} /></label><p className="pack-settings-help">Overrides are limited to approved terminology and theme fields. Permissions, scheduling invariants, and security cannot be changed here.</p><div className="pack-settings-actions"><button className="primary-button" type="button" disabled={!selectedPack || busy} onClick={() => void save()}>{saving ? "Saving..." : "Save workspace pack"}</button><button className="account-button" type="button" disabled={busy} onClick={() => void materialize()}>{materializing ? "Materializing..." : "Materialize services"}</button></div></div>{selectedPack && <aside className="pack-settings-preview" style={{ "--pack-accent": selectedPack.theme.accent } as React.CSSProperties}><span className="pack-swatch" aria-hidden="true" /><p className="eyebrow">Selected pack</p><h2>{selectedPack.displayName}</h2><p>{selectedPack.serviceTemplates.length} service template{selectedPack.serviceTemplates.length === 1 ? "" : "s"}, {selectedPack.resourceTypes.length} resource type{selectedPack.resourceTypes.length === 1 ? "" : "s"}, {selectedPack.capabilities.length} capabilities.</p></aside>}</article></>}</section></WorkspaceShell>;
}
