// Ownership: authenticated route creation form; ordered stops are validated again by the API.
"use client";

import { useState, type FormEvent } from "react";
import { createTransportRoute } from "../../src/transport-staff-client.js";
import { apiBase } from "./workspace-admission.js";

type RouteInput = { name: string; mode: "bus" | "matatu" | "shuttle" | "charter"; status: "draft" | "published" | "archived"; stops: readonly { stopId: string; sequence: number; boardingMinutes: number; alightingMinutes: number }[] };
type Props = { tenantId: string; onCreated: (route: RouteInput & { id: string; tenantId: string; version: number }) => void; onMessage: (message: string, kind?: "error" | "ready") => void };
function readStops(value: string): RouteInput["stops"] { return value.split(/[\n,]/u).map((item) => item.trim()).filter(Boolean).map((stopId, index) => ({ stopId, sequence: index + 1, boardingMinutes: 5, alightingMinutes: 5 })); }

export function TransportRouteForm({ tenantId, onCreated, onMessage }: Props) {
  const [name, setName] = useState(""); const [mode, setMode] = useState<RouteInput["mode"]>("bus"); const [status, setStatus] = useState<RouteInput["status"]>("draft"); const [stops, setStops] = useState(""); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const orderedStops = readStops(stops); if (orderedStops.length < 2) return onMessage("Add at least two ordered stops, separated by commas or new lines.", "error"); setPending(true); try { const result = await createTransportRoute(window.fetch.bind(window), apiBase, tenantId, { name: name.trim(), mode, status, stops: orderedStops }); if (result.kind !== "ready") return onMessage(result.message, "error"); onCreated(result.value); setName(""); setStops(""); onMessage(`${result.value.name} was created.`, "ready"); } catch { onMessage("The route could not be created. Check your connection and try again.", "error"); } finally { setPending(false); } }
  return <form className="transport-staff-form" onSubmit={(event) => void submit(event)} aria-busy={pending}><div className="transport-form-heading"><p className="eyebrow">Route setup</p><h2>Create a route</h2><p>Keep the stop order stable for every published trip.</p></div><label>Route name<input required maxLength={200} value={name} onChange={(event) => setName(event.target.value)} disabled={pending} placeholder="Town to Airport" /></label><div className="transport-form-grid"><label>Mode<select value={mode} onChange={(event) => setMode(event.target.value as RouteInput["mode"])} disabled={pending}><option value="bus">Bus</option><option value="matatu">Matatu</option><option value="shuttle">Shuttle</option><option value="charter">Charter</option></select></label><label>Visibility<select value={status} onChange={(event) => setStatus(event.target.value as RouteInput["status"])} disabled={pending}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div><label>Stops in order<textarea required rows={3} value={stops} onChange={(event) => setStops(event.target.value)} disabled={pending} placeholder="Town, Market, Airport" /></label><button className="primary-button" type="submit" disabled={pending}>{pending ? "Creating..." : "Create route"}</button></form>;
}
