// Ownership: authenticated dated-trip creation form; trip identity remains bound to a route version and occurrence.
"use client";

import { useEffect, useState, type FormEvent } from "react";
import type { TransportRouteSummary } from "@bookingapp/contracts";
import { createTransportTrip } from "../../src/transport-staff-client.js";
import { apiBase } from "./workspace-admission.js";

type Props = { tenantId: string; routes: readonly TransportRouteSummary[]; onCreated: () => void; onMessage: (message: string, kind?: "error" | "ready") => void };
function localDateTime(date: Date): string { return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

export function TransportTripForm({ tenantId, routes, onCreated, onMessage }: Props) {
  const [routeId, setRouteId] = useState(routes[0]?.id ?? ""); const [occurrenceId, setOccurrenceId] = useState(""); const [capacityMode, setCapacityMode] = useState<"seat" | "open">("seat"); const [capacity, setCapacity] = useState("14"); const [startsAt, setStartsAt] = useState(localDateTime(new Date(Date.now() + 60 * 60 * 1000))); const [endsAt, setEndsAt] = useState(localDateTime(new Date(Date.now() + 2 * 60 * 60 * 1000))); const [vehicleResourceId, setVehicleResourceId] = useState(""); const [pending, setPending] = useState(false);
  useEffect(() => { if (!routeId && routes[0]) setRouteId(routes[0].id); }, [routeId, routes]);
  const route = routes.find((item) => item.id === routeId);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const count = Number(capacity); const start = new Date(startsAt); const end = new Date(endsAt); if (!route || !occurrenceId.trim() || !Number.isInteger(count) || count < 1 || Number.isNaN(start.getTime()) || Number.isNaN(end.getTime()) || end <= start) return onMessage("Choose a route, occurrence, capacity, and valid boarding window.", "error"); setPending(true); try { const result = await createTransportTrip(window.fetch.bind(window), apiBase, tenantId, { routeId: route.id, routeVersion: route.version, occurrenceId: occurrenceId.trim(), capacityMode, capacity: count, boardingStartsAt: start.toISOString(), boardingEndsAt: end.toISOString(), vehicleResourceId: vehicleResourceId.trim() || null }); if (result.kind !== "ready") return onMessage(result.message, "error"); setOccurrenceId(""); onCreated(); onMessage("The trip was created.", "ready"); } catch { onMessage("The trip could not be created. Check the route and time window, then try again.", "error"); } finally { setPending(false); } }
  return <form className="transport-staff-form" onSubmit={(event) => void submit(event)} aria-busy={pending}><div className="transport-form-heading"><p className="eyebrow">Trip planning</p><h2>Publish a dated trip</h2><p>Use the occurrence ID from the shared schedule.</p></div><label>Route<select required value={routeId} onChange={(event) => setRouteId(event.target.value)} disabled={pending || !routes.length}><option value="">Choose a route</option>{routes.map((item) => <option key={item.id} value={item.id}>{item.name} - v{item.version}</option>)}</select></label><label>Occurrence ID<input required maxLength={200} value={occurrenceId} onChange={(event) => setOccurrenceId(event.target.value)} disabled={pending} placeholder="occurrence-id" /></label><div className="transport-form-grid"><label>Capacity mode<select value={capacityMode} onChange={(event) => setCapacityMode(event.target.value as "seat" | "open")} disabled={pending}><option value="seat">Seat-based</option><option value="open">Open capacity</option></select></label><label>Capacity<input required type="number" min="1" step="1" value={capacity} onChange={(event) => setCapacity(event.target.value)} disabled={pending} /></label></div><div className="transport-form-grid"><label>Boarding starts<input required type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} disabled={pending} /></label><label>Boarding ends<input required type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} disabled={pending} /></label></div><label>Vehicle resource ID <span className="field-optional">optional</span><input maxLength={120} value={vehicleResourceId} onChange={(event) => setVehicleResourceId(event.target.value)} disabled={pending} placeholder="vehicle-resource-id" /></label><button className="primary-button" type="submit" disabled={pending || !routes.length}>{pending ? "Creating..." : "Create trip"}</button></form>;
}
