// Ownership: tenant-safe public manage capability. Tokens are signed, opaque, and database-revocable.

import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import type { Pool } from "pg";
import { bookingChangeAllowed, defaultBookingChangePolicy, type Booking } from "@bookingapp/domain";
import { withTenantTransaction } from "./pg-executor.js";
import type { SqlExecutor } from "./tenant-membership.js";
import { readCommunicationSettings } from "./communications.js";

interface BookingRow { id: string; tenant_id: string; customer_id: string; service_name: string; starts_at: Date; ends_at: Date; status: Booking["status"]; resource_ids?: string[]; manage_token_hash?: string; manage_token_expires_at?: Date | null; }
interface TokenPayload { tenantId: string; bookingId: string; }
const hash = (value: string): string => createHash("sha256").update(value).digest("hex");
const sign = (payload: string, secret: string): string => createHmac("sha256", secret).update(payload).digest("base64url");
function map(row: BookingRow): Booking { return { id: row.id, tenantId: row.tenant_id, customerId: row.customer_id, serviceName: row.service_name, startsAt: new Date(row.starts_at), endsAt: new Date(row.ends_at), status: row.status, ...(row.resource_ids?.length ? { resourceIds: row.resource_ids } : {}) }; }
function tokenFor(secret: string, tenantId: string, bookingId: string): string { const payload = Buffer.from(JSON.stringify({ tenantId, bookingId })).toString("base64url"); return `${payload}.${sign(payload, secret)}`; }
function parse(token: string, secret: string): TokenPayload | null { const [payload, signature] = token.split("."); const expected = payload ? sign(payload, secret) : ""; if (!payload || !signature || expected.length !== signature.length || !timingSafeEqual(Buffer.from(expected), Buffer.from(signature))) return null; try { const value = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")) as TokenPayload; return value.tenantId && value.bookingId ? value : null; } catch { return null; } }
async function readForUpdate(executor: SqlExecutor, payload: TokenPayload, token: string): Promise<BookingRow | null> { const rows = await executor.query<BookingRow>("SELECT id, tenant_id, customer_id, service_name, starts_at, ends_at, status, manage_token_hash, manage_token_expires_at FROM bookings WHERE tenant_id = $1 AND id = $2 AND manage_token_hash = $3 AND manage_token_expires_at > now() FOR UPDATE", [payload.tenantId, payload.bookingId, hash(token)]); if (!rows[0]) return null; const resources = await executor.query<{ resource_id: string }>("SELECT resource_id FROM booking_resource_allocations WHERE tenant_id = $1 AND booking_id = $2 AND status = 'scheduled' ORDER BY resource_id", [payload.tenantId, payload.bookingId]); return { ...rows[0], resource_ids: resources.map((resource) => resource.resource_id) }; }
async function changePolicy(executor: SqlExecutor, tenantId: string) { return (await readCommunicationSettings(executor, tenantId))?.bookingChangePolicy ?? defaultBookingChangePolicy; }
export async function issueBookingManageToken(executor: SqlExecutor, booking: Booking, secret: string): Promise<string> { const token = tokenFor(secret, booking.tenantId, booking.id); const expiresAt = new Date(Math.max(booking.endsAt.getTime(), Date.now()) + 90 * 24 * 60 * 60 * 1000); const rows = await executor.query<{ id: string }>("UPDATE bookings SET manage_token_hash = $1, manage_token_expires_at = $2, updated_at = now() WHERE tenant_id = $3 AND id = $4 RETURNING id", [hash(token), expiresAt, booking.tenantId, booking.id]); if (!rows[0]) throw new Error("Manage capability could not be issued"); return token; }
async function claimAction(executor: SqlExecutor, booking: BookingRow, action: "reschedule" | "cancel", idempotencyKey: string, payloadHash: string): Promise<boolean> { const inserted = await executor.query<{ idempotency_key: string }>("INSERT INTO booking_manage_actions (tenant_id, booking_id, idempotency_key, action, payload_hash) VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING RETURNING idempotency_key", [booking.tenant_id, booking.id, idempotencyKey, action, payloadHash]); if (inserted[0]) return true; const existing = await executor.query<{ action: string; payload_hash: string }>("SELECT action, payload_hash FROM booking_manage_actions WHERE tenant_id = $1 AND idempotency_key = $2", [booking.tenant_id, idempotencyKey]); if (!existing[0] || existing[0].action !== action || existing[0].payload_hash !== payloadHash) throw new Error("Manage action idempotency key was already used"); return false; }
export function createBookingManageAdapter(pool: Pool, secret: string) {
  return {
    read: async (token: string): Promise<Booking | null> => { const payload = parse(token, secret); if (!payload) return null; return withTenantTransaction(pool, payload.tenantId, async (executor) => { const row = await readForUpdate(executor, payload, token); return row ? map(row) : null; }); },
    reschedule: async (token: string, startsAt: Date, endsAt: Date, idempotencyKey: string): Promise<Booking | null> => { const payload = parse(token, secret); if (!payload || Number.isNaN(startsAt.getTime()) || Number.isNaN(endsAt.getTime()) || endsAt <= startsAt || startsAt <= new Date()) return null; return withTenantTransaction(pool, payload.tenantId, async (executor) => { const row = await readForUpdate(executor, payload, token); if (!row || row.status !== "scheduled") return null; const now = new Date(); const policy = await changePolicy(executor, row.tenant_id); if (!bookingChangeAllowed(policy, "reschedule", row.starts_at, now) || !bookingChangeAllowed(policy, "reschedule", startsAt, now)) throw new Error(policy.rescheduleEnabled ? "This appointment is outside the organization's rescheduling notice window" : "Rescheduling is disabled for this organization"); const changed = await claimAction(executor, row, "reschedule", idempotencyKey, hash(`reschedule:${startsAt.toISOString()}:${endsAt.toISOString()}`)); if (!changed) return map(row); const updated = await executor.query<BookingRow>("UPDATE bookings SET starts_at = $1, ends_at = $2, manage_token_expires_at = $3, updated_at = now() WHERE tenant_id = $4 AND id = $5 RETURNING id, tenant_id, customer_id, service_name, starts_at, ends_at, status", [startsAt, endsAt, new Date(endsAt.getTime() + 90 * 24 * 60 * 60 * 1000), row.tenant_id, row.id]); await executor.query("UPDATE booking_resource_allocations SET starts_at = $1, ends_at = $2 WHERE tenant_id = $3 AND booking_id = $4 AND status = 'scheduled'", [startsAt, endsAt, row.tenant_id, row.id]); return updated[0] ? map({ ...updated[0], resource_ids: row.resource_ids ?? [] }) : null; }); },
    cancel: async (token: string, idempotencyKey: string): Promise<Booking | null> => { const payload = parse(token, secret); if (!payload) return null; return withTenantTransaction(pool, payload.tenantId, async (executor) => { const row = await readForUpdate(executor, payload, token); if (!row || row.status !== "scheduled") return row ? map(row) : null; const policy = await changePolicy(executor, row.tenant_id); if (!bookingChangeAllowed(policy, "cancel", row.starts_at)) throw new Error(policy.cancellationEnabled ? "This appointment is outside the organization's cancellation notice window" : "Cancellation is disabled for this organization"); const changed = await claimAction(executor, row, "cancel", idempotencyKey, hash("cancel")); if (!changed) return map(row); const updated = await executor.query<BookingRow>("UPDATE bookings SET status = 'cancelled', updated_at = now() WHERE tenant_id = $1 AND id = $2 RETURNING id, tenant_id, customer_id, service_name, starts_at, ends_at, status", [row.tenant_id, row.id]); await executor.query("UPDATE booking_resource_allocations SET status = 'cancelled' WHERE tenant_id = $1 AND booking_id = $2", [row.tenant_id, row.id]); return updated[0] ? map({ ...updated[0], resource_ids: row.resource_ids ?? [] }) : null; }); },
  };
}
