// Ownership: tenant-managed GTFS-Realtime alert source tied to an active Schedule.

import { randomUUID } from "node:crypto";
import { validateGtfsRealtimeAlert, type GtfsPublishedReferences, type GtfsRealtimeAlert } from "@bookingapp/domain";
import type { SqlExecutor } from "./tenant-membership.js";

export type GtfsAlertStatus = "draft" | "published" | "withdrawn";
export interface GtfsAlertRecord extends GtfsRealtimeAlert { readonly tenantId: string; readonly feedVersionId: string; readonly status: GtfsAlertStatus; readonly createdAt: Date; }
export interface GtfsAlertDraft { readonly tenantId: string; readonly headerText: string; readonly descriptionText?: string; readonly activeFrom?: Date; readonly activeUntil?: Date; readonly routePublicIds?: readonly string[]; readonly stopPublicIds?: readonly string[]; readonly tripPublicIds?: readonly string[]; readonly createdBy?: string | null; }

interface AlertRow { id: string; tenant_id: string; feed_version_id: string; header_text: string; description_text: string | null; active_from: Date | null; active_until: Date | null; route_public_ids: string[]; stop_public_ids: string[]; trip_public_ids: string[]; status: GtfsAlertStatus; created_at: Date; }
interface ReferenceRow { entity_kind: "route" | "trip" | "stop"; public_id: string; }

function mapAlert(row: AlertRow): GtfsAlertRecord { return { entityPublicId: row.id, tenantId: row.tenant_id, feedVersionId: row.feed_version_id, headerText: row.header_text, ...(row.description_text ? { descriptionText: row.description_text } : {}), ...(row.active_from ? { activeFrom: new Date(row.active_from) } : {}), ...(row.active_until ? { activeUntil: new Date(row.active_until) } : {}), ...(row.route_public_ids.length ? { routePublicIds: row.route_public_ids } : {}), ...(row.stop_public_ids.length ? { stopPublicIds: row.stop_public_ids } : {}), ...(row.trip_public_ids.length ? { tripPublicIds: row.trip_public_ids } : {}), status: row.status, createdAt: new Date(row.created_at) }; }
function refs(rows: readonly ReferenceRow[], scheduleVersion: string): GtfsPublishedReferences { return { scheduleVersion, routeIds: new Set(rows.filter((row) => row.entity_kind === "route").map((row) => row.public_id)), tripIds: new Set(rows.filter((row) => row.entity_kind === "trip").map((row) => row.public_id)), stopIds: new Set(rows.filter((row) => row.entity_kind === "stop").map((row) => row.public_id)) }; }

async function activeFeed(executor: SqlExecutor, tenantId: string): Promise<{ feedVersionId: string; version: string } | null> { const row = (await executor.query<{ feed_version_id: string; version: string }>("SELECT version.id AS feed_version_id, version.version FROM gtfs_feed_settings settings JOIN gtfs_feed_versions version ON version.tenant_id = settings.tenant_id AND version.id = settings.active_version_id WHERE settings.tenant_id = $1 AND settings.schedule_publication_enabled = true AND version.status = 'published'", [tenantId]))[0]; return row ? { feedVersionId: row.feed_version_id, version: row.version } : null; }
async function activeRefs(executor: SqlExecutor, tenantId: string, feedVersionId: string, version: string): Promise<GtfsPublishedReferences> { return refs(await executor.query<ReferenceRow>("SELECT entity_kind, public_id FROM gtfs_feed_version_entities WHERE tenant_id = $1 AND feed_version_id = $2", [tenantId, feedVersionId]), version); }

export async function listGtfsAlerts(executor: SqlExecutor, tenantId: string): Promise<readonly GtfsAlertRecord[]> { const rows = await executor.query<AlertRow>("SELECT id, tenant_id, feed_version_id, header_text, description_text, active_from, active_until, route_public_ids, stop_public_ids, trip_public_ids, status, created_at FROM gtfs_realtime_alerts WHERE tenant_id = $1 ORDER BY created_at DESC, id DESC", [tenantId]); return rows.map(mapAlert); }

export async function createGtfsAlert(executor: SqlExecutor, input: GtfsAlertDraft): Promise<GtfsAlertRecord> {
  const feed = await activeFeed(executor, input.tenantId); if (!feed) throw new Error("GTFS_ALERT_SCHEDULE_REQUIRED");
  const alert: GtfsRealtimeAlert = { entityPublicId: `alert-${randomUUID()}`, headerText: input.headerText.trim(), ...(input.descriptionText?.trim() ? { descriptionText: input.descriptionText.trim() } : {}), ...(input.activeFrom ? { activeFrom: input.activeFrom } : {}), ...(input.activeUntil ? { activeUntil: input.activeUntil } : {}), ...(input.routePublicIds?.length ? { routePublicIds: input.routePublicIds } : {}), ...(input.stopPublicIds?.length ? { stopPublicIds: input.stopPublicIds } : {}), ...(input.tripPublicIds?.length ? { tripPublicIds: input.tripPublicIds } : {}) };
  const errors = validateGtfsRealtimeAlert(alert, await activeRefs(executor, input.tenantId, feed.feedVersionId, feed.version)); if (errors.length) throw new Error(`GTFS_ALERT_INVALID:${errors.join("; ")}`);
  const rows = await executor.query<AlertRow>("INSERT INTO gtfs_realtime_alerts (id, tenant_id, feed_version_id, header_text, description_text, active_from, active_until, route_public_ids, stop_public_ids, trip_public_ids, created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id, tenant_id, feed_version_id, header_text, description_text, active_from, active_until, route_public_ids, stop_public_ids, trip_public_ids, status, created_at", [alert.entityPublicId, input.tenantId, feed.feedVersionId, alert.headerText, alert.descriptionText ?? null, alert.activeFrom ?? null, alert.activeUntil ?? null, alert.routePublicIds ?? [], alert.stopPublicIds ?? [], alert.tripPublicIds ?? [], input.createdBy ?? null]);
  if (!rows[0]) throw new Error("GTFS_ALERT_UNAVAILABLE"); return mapAlert(rows[0]);
}

export async function setGtfsAlertStatus(executor: SqlExecutor, input: { tenantId: string; alertId: string; status: Exclude<GtfsAlertStatus, "draft"> }): Promise<GtfsAlertRecord | null> { const rows = await executor.query<AlertRow>("UPDATE gtfs_realtime_alerts SET status = $3, updated_at = now() WHERE tenant_id = $1 AND id = $2 RETURNING id, tenant_id, feed_version_id, header_text, description_text, active_from, active_until, route_public_ids, stop_public_ids, trip_public_ids, status, created_at", [input.tenantId, input.alertId, input.status]); return rows[0] ? mapAlert(rows[0]) : null; }
