import assert from "node:assert/strict";
import test from "node:test";
import { createIndustryPackRegistry, DRIVING_SCHOOL_PACK } from "@bookingapp/domain";
import { materializeIndustryPack, readIndustryPackSelection, saveIndustryPackSelection } from "./industry-pack-settings.js";

const row = { tenant_id: "tenant-1", pack_id: "driving-school", pack_version: "1.0.0", overrides: { terminology: { service: "Lesson" } } };
test("reads and saves a tenant pack selection with audit evidence", async () => { const calls: string[] = []; const executor = { query: async <T>(sql: string) => { calls.push(sql); return sql.startsWith("SELECT") ? [row] as T[] : [] as T[]; } }; assert.equal((await readIndustryPackSelection(executor, "tenant-1"))?.packId, "driving-school"); const saved = await saveIndustryPackSelection(executor, { tenantId: "tenant-1", packId: DRIVING_SCHOOL_PACK.id, packVersion: DRIVING_SCHOOL_PACK.version, overrides: { terminology: { service: "Lesson" } } }, "user-1"); assert.equal(saved.overrides.terminology?.service, "Lesson"); assert.ok(calls.some((sql) => sql.includes("industry_pack_events"))); });
test("rejects an unregistered pack version before persistence", async () => { const executor = { query: async <T>() => [] as T[] }; await assert.rejects(() => saveIndustryPackSelection(executor, { tenantId: "tenant-1", packId: "missing-pack", packVersion: "1.0.0", overrides: {} }, null), /not registered/iu); });
test("records upgrade and downgrade transitions without changing event action compatibility", async () => { const newer = { ...DRIVING_SCHOOL_PACK, version: "1.1.0" as const }; const registry = createIndustryPackRegistry([DRIVING_SCHOOL_PACK, newer]); const transitions: string[] = []; const executor = (current: typeof row) => ({ query: async <T>(sql: string, args?: readonly unknown[]) => { if (sql.startsWith("SELECT")) return [current] as T[]; if (sql.includes("industry_pack_events")) { const metadata = args?.[6]; if (typeof metadata === "string") transitions.push(JSON.parse(metadata).transition); } return [] as T[]; } }); await saveIndustryPackSelection(executor(row), { tenantId: "tenant-1", packId: "driving-school", packVersion: "1.1.0", overrides: {} }, "user-1", registry); await saveIndustryPackSelection(executor({ ...row, pack_version: "1.1.0" }), { tenantId: "tenant-1", packId: "driving-school", packVersion: "1.0.0", overrides: {} }, "user-1", registry); assert.deepEqual(transitions, ["upgrade", "downgrade"]); });
test("materializes a selected pack idempotently as catalog composition", async () => { const executor = { query: async <T>(sql: string) => { if (sql.startsWith("SELECT")) return [row] as T[]; if (sql.includes("industry_pack_events")) return [] as T[]; return [{ id: "created" }] as T[]; } }; const result = await materializeIndustryPack(executor, "tenant-1", "user-1"); assert.deepEqual(result, { tenantId: "tenant-1", packId: "driving-school", packVersion: "1.0.0", createdServices: 1, createdVariants: 1, createdRequirements: 2 }); });
