// Ownership: tenant pack selection persistence; registry validation stays authoritative in domain.

import { buildIndustryPackMaterializationPlan, defaultIndustryPackRegistry, validateIndustryPackOverrides, type IndustryPackOverrides, type IndustryPackSelection, type IndustryPackRegistry } from "@bookingapp/domain";
import type { Pool } from "pg";
import { randomUUID } from "node:crypto";
import { withTenantTransaction } from "./pg-executor.js";
import type { SqlExecutor } from "./tenant-membership.js";

interface SelectionRow { tenant_id: string; pack_id: string; pack_version: string; overrides: IndustryPackOverrides; }
function map(row: SelectionRow): IndustryPackSelection { return { tenantId: row.tenant_id, packId: row.pack_id, packVersion: row.pack_version, overrides: row.overrides ?? {} }; }
function compareVersions(left: string, right: string): number { const a = left.split(".").map(Number); const b = right.split(".").map(Number); return (a[0] ?? 0) - (b[0] ?? 0) || (a[1] ?? 0) - (b[1] ?? 0) || (a[2] ?? 0) - (b[2] ?? 0); }
function selectionTransition(previous: IndustryPackSelection | null, next: IndustryPackSelection): "initial" | "upgrade" | "downgrade" | "same_version" | "pack_changed" { if (!previous) return "initial"; if (previous.packId !== next.packId) return "pack_changed"; const comparison = compareVersions(next.packVersion, previous.packVersion); return comparison > 0 ? "upgrade" : comparison < 0 ? "downgrade" : "same_version"; }
export async function readIndustryPackSelection(executor: SqlExecutor, tenantId: string): Promise<IndustryPackSelection | null> { const rows = await executor.query<SelectionRow>("SELECT tenant_id, pack_id, pack_version, overrides FROM industry_pack_settings WHERE tenant_id = $1", [tenantId]); return rows[0] ? map(rows[0]) : null; }
export async function saveIndustryPackSelection(executor: SqlExecutor, input: IndustryPackSelection, actorId: string | null, registry: IndustryPackRegistry = defaultIndustryPackRegistry): Promise<IndustryPackSelection> { const pack = registry.read(input.packId, input.packVersion); if (!pack) throw new Error("Selected industry pack version is not registered"); const errors = validateIndustryPackOverrides(pack, input.overrides); if (errors.length) throw new Error(errors.join("; ")); const previous = await readIndustryPackSelection(executor, input.tenantId); const transition = selectionTransition(previous, input); await executor.query("INSERT INTO industry_pack_settings (tenant_id, pack_id, pack_version, overrides) VALUES ($1,$2,$3,$4::jsonb) ON CONFLICT (tenant_id) DO UPDATE SET pack_id = EXCLUDED.pack_id, pack_version = EXCLUDED.pack_version, overrides = EXCLUDED.overrides, updated_at = now()", [input.tenantId, input.packId, input.packVersion, JSON.stringify(input.overrides)]); await executor.query("INSERT INTO industry_pack_events (id, tenant_id, actor_id, action, pack_id, pack_version, metadata) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb)", [randomUUID(), input.tenantId, actorId, previous ? "overrides_updated" : "selected", input.packId, input.packVersion, JSON.stringify({ previousPackId: previous?.packId ?? null, previousPackVersion: previous?.packVersion ?? null, transition })]); return input; }
export interface IndustryPackMaterializationSummary { tenantId: string; packId: string; packVersion: string; createdServices: number; createdVariants: number; createdRequirements: number; }
export async function materializeIndustryPack(executor: SqlExecutor, tenantId: string, actorId: string | null, registry: IndustryPackRegistry = defaultIndustryPackRegistry): Promise<IndustryPackMaterializationSummary> { const selection = await readIndustryPackSelection(executor, tenantId); if (!selection) throw new Error("Select an industry pack before materializing services"); const pack = registry.read(selection.packId, selection.packVersion); if (!pack) throw new Error("Selected industry pack version is not registered"); const plan = buildIndustryPackMaterializationPlan(pack, tenantId); let createdServices = 0; let createdVariants = 0; let createdRequirements = 0; for (const service of plan.services) { const rows = await executor.query<{ id: string }>("INSERT INTO service_definitions (id, tenant_id, name, description, booking_mode, duration_minutes, buffer_before_minutes, buffer_after_minutes, price_cents, currency, pack_id, pack_version, status) VALUES ($1,$2,$3,NULL,$4,$5,0,0,NULL,NULL,$6,$7,'active') ON CONFLICT (tenant_id, id) DO NOTHING RETURNING id", [service.id, service.tenantId, service.name, service.bookingMode, service.durationMinutes, pack.id, pack.version]); createdServices += rows.length; } for (const variant of plan.variants) { const rows = await executor.query<{ id: string }>("INSERT INTO service_variants (id, tenant_id, service_id, name, duration_minutes, buffer_before_minutes, buffer_after_minutes, price_cents, currency, status, pack_id, pack_version) VALUES ($1,$2,$3,$4,NULL,NULL,NULL,NULL,NULL,'active',$5,$6) ON CONFLICT (tenant_id, id) DO NOTHING RETURNING id", [variant.id, variant.tenantId, variant.serviceId, variant.name, pack.id, pack.version]); createdVariants += rows.length; } for (const requirement of plan.requirements) { const rows = await executor.query<{ id: string }>("INSERT INTO service_requirements (id, tenant_id, service_id, variant_id, kind, label, quantity, resource_type, capability_key, status, pack_id, pack_version) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'active',$10,$11) ON CONFLICT (tenant_id, id) DO NOTHING RETURNING id", [requirement.id, requirement.tenantId, requirement.serviceId, requirement.variantId ?? null, requirement.kind, requirement.label, requirement.quantity ?? 1, requirement.resourceType ?? null, requirement.capabilityKey ?? null, pack.id, pack.version]); createdRequirements += rows.length; } await executor.query("INSERT INTO industry_pack_events (id, tenant_id, actor_id, action, pack_id, pack_version, metadata) VALUES ($1,$2,$3,'materialized',$4,$5,$6::jsonb)", [randomUUID(), tenantId, actorId, pack.id, pack.version, JSON.stringify({ createdServices, createdVariants, createdRequirements })]); return { tenantId, packId: pack.id, packVersion: pack.version, createdServices, createdVariants, createdRequirements }; }
export function createDatabaseIndustryPackAdmin(pool: Pool) { return { read: (tenantId: string) => withTenantTransaction(pool, tenantId, (executor) => readIndustryPackSelection(executor, tenantId)), save: (input: IndustryPackSelection, actorId: string | null) => withTenantTransaction(pool, input.tenantId, (executor) => saveIndustryPackSelection(executor, input, actorId)), materialize: (tenantId: string, actorId: string | null) => withTenantTransaction(pool, tenantId, (executor) => materializeIndustryPack(executor, tenantId, actorId)) }; }
