// Ownership: tenant-scoped service catalog persistence; validation stays in the domain package.

import { validateServiceDefinitionDraft, type ServiceDefinition, type ServiceDefinitionDraft } from "@bookingapp/domain";
import type { Pool } from "pg";
import { withTenantTransaction } from "./pg-executor.js";
import type { SqlExecutor } from "./tenant-membership.js";

interface ServiceRow { id: string; tenant_id: string; name: string; description: string | null; booking_mode: ServiceDefinition["bookingMode"]; duration_minutes: number; buffer_before_minutes: number; buffer_after_minutes: number; price_cents: number | null; currency: string | null; pack_id: string | null; status: ServiceDefinition["status"]; }
function map(row: ServiceRow): ServiceDefinition { return { id: row.id, tenantId: row.tenant_id, name: row.name, description: row.description, bookingMode: row.booking_mode, durationMinutes: row.duration_minutes, bufferBeforeMinutes: row.buffer_before_minutes, bufferAfterMinutes: row.buffer_after_minutes, priceCents: row.price_cents, currency: row.currency, packId: row.pack_id, status: row.status }; }
const columns = "id, tenant_id, name, description, booking_mode, duration_minutes, buffer_before_minutes, buffer_after_minutes, price_cents, currency, pack_id, status";
export async function listServices(executor: SqlExecutor, tenantId: string): Promise<readonly ServiceDefinition[]> { const rows = await executor.query<ServiceRow>(`SELECT ${columns} FROM service_definitions WHERE tenant_id = $1 ORDER BY status, name, id`, [tenantId]); return rows.map(map); }
export async function createService(executor: SqlExecutor, draft: ServiceDefinitionDraft): Promise<ServiceDefinition> { const errors = validateServiceDefinitionDraft(draft); if (errors.length) throw new Error(errors.join("; ")); const rows = await executor.query<ServiceRow>(`INSERT INTO service_definitions (${columns}) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'active') RETURNING ${columns}`, [draft.id, draft.tenantId, draft.name.trim(), draft.description?.trim() || null, draft.bookingMode, draft.durationMinutes, draft.bufferBeforeMinutes ?? 0, draft.bufferAfterMinutes ?? 0, draft.priceCents ?? null, draft.currency ?? null, draft.packId?.trim() || null]); if (!rows[0]) throw new Error("Service creation returned no row"); return map(rows[0]); }
export async function setServiceStatus(executor: SqlExecutor, tenantId: string, serviceId: string, status: "active" | "inactive"): Promise<boolean> { const rows = await executor.query<{ id: string }>("UPDATE service_definitions SET status = $1, updated_at = now() WHERE tenant_id = $2 AND id = $3 RETURNING id", [status, tenantId, serviceId]); return rows.length > 0; }
export function createDatabaseServiceAdmin(pool: Pool) { return { list: (tenantId: string) => withTenantTransaction(pool, tenantId, (executor) => listServices(executor, tenantId)), create: (input: ServiceDefinitionDraft) => withTenantTransaction(pool, input.tenantId, (executor) => createService(executor, input)), setStatus: (tenantId: string, serviceId: string, status: "active" | "inactive") => withTenantTransaction(pool, tenantId, (executor) => setServiceStatus(executor, tenantId, serviceId, status)) }; }
