// Ownership: tenant-scoped service composition persistence; scheduling owns allocation.

import { validateServiceRequirementDraft, validateServiceVariantDraft, type ServiceRequirement, type ServiceRequirementDraft, type ServiceVariant, type ServiceVariantDraft } from "@bookingapp/domain";
import type { Pool } from "pg";
import { withTenantTransaction } from "./pg-executor.js";
import type { SqlExecutor } from "./tenant-membership.js";

interface VariantRow { id: string; tenant_id: string; service_id: string; name: string; duration_minutes: number | null; buffer_before_minutes: number | null; buffer_after_minutes: number | null; price_cents: number | null; currency: string | null; status: ServiceVariant["status"]; }
interface RequirementRow { id: string; tenant_id: string; service_id: string; variant_id: string | null; kind: ServiceRequirement["kind"]; label: string; quantity: number; resource_type: string | null; capability_key: string | null; status: ServiceRequirement["status"]; }
const variantColumns = "id, tenant_id, service_id, name, duration_minutes, buffer_before_minutes, buffer_after_minutes, price_cents, currency, status";
const requirementColumns = "id, tenant_id, service_id, variant_id, kind, label, quantity, resource_type, capability_key, status";
const mapVariant = (row: VariantRow): ServiceVariant => ({ id: row.id, tenantId: row.tenant_id, serviceId: row.service_id, name: row.name, durationMinutes: row.duration_minutes, bufferBeforeMinutes: row.buffer_before_minutes, bufferAfterMinutes: row.buffer_after_minutes, priceCents: row.price_cents, currency: row.currency, status: row.status });
const mapRequirement = (row: RequirementRow): ServiceRequirement => ({ id: row.id, tenantId: row.tenant_id, serviceId: row.service_id, variantId: row.variant_id, kind: row.kind, label: row.label, quantity: row.quantity, resourceType: row.resource_type, capabilityKey: row.capability_key, status: row.status });

export async function listServiceVariants(executor: SqlExecutor, tenantId: string, serviceId: string): Promise<readonly ServiceVariant[]> { const rows = await executor.query<VariantRow>(`SELECT ${variantColumns} FROM service_variants WHERE tenant_id = $1 AND service_id = $2 ORDER BY status, name, id`, [tenantId, serviceId]); return rows.map(mapVariant); }
export async function createServiceVariant(executor: SqlExecutor, draft: ServiceVariantDraft): Promise<ServiceVariant> { const errors = validateServiceVariantDraft(draft); if (errors.length) throw new Error(errors.join("; ")); const rows = await executor.query<VariantRow>(`INSERT INTO service_variants (${variantColumns}) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'active') RETURNING ${variantColumns}`, [draft.id, draft.tenantId, draft.serviceId, draft.name.trim(), draft.durationMinutes ?? null, draft.bufferBeforeMinutes ?? null, draft.bufferAfterMinutes ?? null, draft.priceCents ?? null, draft.currency ?? null]); if (!rows[0]) throw new Error("Variant creation returned no row"); return mapVariant(rows[0]); }
export async function setServiceVariantStatus(executor: SqlExecutor, tenantId: string, variantId: string, status: ServiceVariant["status"]): Promise<boolean> { const rows = await executor.query<{ id: string }>("UPDATE service_variants SET status = $1, updated_at = now() WHERE tenant_id = $2 AND id = $3 RETURNING id", [status, tenantId, variantId]); return rows.length > 0; }
export async function listServiceRequirements(executor: SqlExecutor, tenantId: string, serviceId: string, variantId?: string | null): Promise<readonly ServiceRequirement[]> { const rows = await executor.query<RequirementRow>(`SELECT ${requirementColumns} FROM service_requirements WHERE tenant_id = $1 AND service_id = $2 AND ($3::text IS NULL OR variant_id = $3) ORDER BY status, label, id`, [tenantId, serviceId, variantId ?? null]); return rows.map(mapRequirement); }
export async function createServiceRequirement(executor: SqlExecutor, draft: ServiceRequirementDraft): Promise<ServiceRequirement> { const errors = validateServiceRequirementDraft(draft); if (errors.length) throw new Error(errors.join("; ")); const rows = await executor.query<RequirementRow>(`INSERT INTO service_requirements (${requirementColumns}) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'active') RETURNING ${requirementColumns}`, [draft.id, draft.tenantId, draft.serviceId, draft.variantId ?? null, draft.kind, draft.label.trim(), draft.quantity ?? 1, draft.resourceType?.trim() || null, draft.capabilityKey?.trim() || null]); if (!rows[0]) throw new Error("Requirement creation returned no row"); return mapRequirement(rows[0]); }
export async function setServiceRequirementStatus(executor: SqlExecutor, tenantId: string, requirementId: string, status: ServiceRequirement["status"]): Promise<boolean> { const rows = await executor.query<{ id: string }>("UPDATE service_requirements SET status = $1, updated_at = now() WHERE tenant_id = $2 AND id = $3 RETURNING id", [status, tenantId, requirementId]); return rows.length > 0; }
export function createDatabaseServiceCompositionAdmin(pool: Pool) { return { listVariants: (tenantId: string, serviceId: string) => withTenantTransaction(pool, tenantId, (executor) => listServiceVariants(executor, tenantId, serviceId)), createVariant: (input: ServiceVariantDraft) => withTenantTransaction(pool, input.tenantId, (executor) => createServiceVariant(executor, input)), setVariantStatus: (tenantId: string, variantId: string, status: ServiceVariant["status"]) => withTenantTransaction(pool, tenantId, (executor) => setServiceVariantStatus(executor, tenantId, variantId, status)), listRequirements: (tenantId: string, serviceId: string, variantId?: string | null) => withTenantTransaction(pool, tenantId, (executor) => listServiceRequirements(executor, tenantId, serviceId, variantId)), createRequirement: (input: ServiceRequirementDraft) => withTenantTransaction(pool, input.tenantId, (executor) => createServiceRequirement(executor, input)), setRequirementStatus: (tenantId: string, requirementId: string, status: ServiceRequirement["status"]) => withTenantTransaction(pool, tenantId, (executor) => setServiceRequirementStatus(executor, tenantId, requirementId, status)) }; }
